import React, { useRef, useState } from 'react';
import { Image, Pressable, View, type GestureResponderEvent } from 'react-native';
import { openExternalUrl } from '@getpaseo/plugin/client';
import { copyText, Icon, ScrollView, useToast } from '@getpaseo/plugin/client/react-native';
import type { RpcInput } from '@getpaseo/plugin';
import type { agentAction } from '../shared/rpc';
import type { AgentEvent, BlockType, CanvasBlock } from '../shared/model';
import type { CanvasController } from './useCanvas';
import { hasCommunication, newId, propertyValue, safeUrl } from './logic';
import { tokens } from './tokens';
import { withAlpha, type Tone } from './color';
import { Modal, Button, CheckRow, Chip, Field, IconButton, OptionRow, Txt, useUI } from './ui';
import { WebFrame } from './web';
import { Diagram } from './Diagram';
export const visual = (type?: BlockType) => tokens.renderers[type ? type.renderer ?? 'generic' : 'unknown'];
const str = (value: unknown) => typeof value === 'string' ? value : value === undefined ? '' : JSON.stringify(value);
export function Delivery({ event, retry }: { event?: AgentEvent; retry?: () => void }) {
  const u = useUI(); if (!event) return null;
  const text = event.status === 'pending' ? 'En cola' : event.status === 'sent' ? `Enviado · ${new Date(event.createdAt).toLocaleTimeString('es', { hour: '2-digit', minute: '2-digit' })}` : event.status === 'acked' ? 'Recibido por el agente' : 'No se envió';
  return <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 4, alignItems: 'center' }}><Icon name={event.status === 'pending' ? 'Clock' : event.status === 'sent' ? 'Check' : event.status === 'acked' ? 'CheckCheck' : 'CircleAlert'} size={12} color={event.status === 'failed' ? u.c.statusDanger : event.status === 'acked' ? u.c.statusSuccess : u.c.foregroundMuted} /><Txt kind="small" muted>{text}</Txt>{event.status === 'failed' && <><Txt kind="small" numberOfLines={1} style={{ color: u.c.statusDanger }}>{event.error}</Txt>{retry && <Button small label="Reintentar" variant="ghost" onPress={retry} />}</>}</View>;
}
function UrlPreview({ block, selected, select }: { block: CanvasBlock; selected: boolean; select: () => void }) {
  const u = useUI(), toast = useToast(), url = safeUrl(block.data.url), [loaded, setLoaded] = useState(false), [timeout, setTimeoutState] = useState(false);
  React.useEffect(() => { setLoaded(false); setTimeoutState(false); }, [url]);
  const open = () => { if (url) void openExternalUrl(url).catch(e => toast.error(String(e))); };
  if (!url) return <View style={{ minHeight: 96, borderWidth: 1, borderStyle: 'dashed', borderRadius: 6, borderColor: u.c.border, padding: 12, gap: 8 }}><Txt kind="label" muted>Referencia conceptual</Txt><Txt>{str(block.data.description)}</Txt>{block.data.url ? <Txt kind="small" style={{ color: u.c.statusDanger }}>Enlace no válido</Txt> : null}</View>;
  const height = u.compact ? tokens.preview.frame.heightCompact : tokens.preview.frame.height;
  return <View style={{ gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', backgroundColor: u.c.surface2, borderRadius: 6, paddingLeft: 8, minHeight: 28, gap: 6 }}><Icon name="Globe" size={12} color={u.c.foregroundMuted} /><Txt kind="code" selectable numberOfLines={1} ellipsizeMode="middle" muted style={{ flex: 1 }}>{url}</Txt><IconButton label="Abrir vista previa" icon="ExternalLink" onPress={open} /></View>
    {u.layout.platform === 'web' ? <View style={{ height }}><WebFrame url={url} title={block.title || 'Vista previa'} border={u.c.border} surface={u.c.surface2} height={height} onLoaded={() => setLoaded(true)} onTimeout={() => setTimeoutState(true)} />{(!selected || !loaded) && <Pressable accessibilityRole="button" accessibilityLabel="Seleccionar vista previa" onPress={select} style={{ position: 'absolute', inset: 0, backgroundColor: loaded ? 'transparent' : u.c.surface2, alignItems: 'center', justifyContent: 'center' }}>{!loaded && <Txt kind="small" muted>Cargando vista previa…</Txt>}</Pressable>}</View> : <View style={{ height, backgroundColor: u.c.surface0, borderWidth: 1, borderColor: u.c.border, borderRadius: 6, alignItems: 'center', justifyContent: 'center', gap: 12 }}><Icon name="AppWindow" size={24} color={u.c.foregroundMuted} /><Txt kind="small" muted>La vista en vivo se abre en el navegador.</Txt><Button label="Abrir vista previa" small onPress={open} /></View>}
    {timeout && !loaded && <><Txt kind="small" muted>Si no se ve, el sitio puede no permitir incrustarse.</Txt><Button label="Abrir" small variant="ghost" icon="ExternalLink" onPress={open} /></>}<Txt>{str(block.data.description)}</Txt>
  </View>;
}
function FormBody({ block, type, controller: c, submit }: { block: CanvasBlock; type: BlockType; controller: CanvasController; submit: (values: CanvasBlock['data']) => Promise<void> }) {
  const values = useRef<Record<string, unknown>>(Object.fromEntries(type.properties.map(p => [p.key, p.kind === 'json' ? JSON.stringify(block.data[p.key] ?? null, null, 2) : block.data[p.key] ?? '']))), dirty = useRef(new Set<string>());
  const [submitting, setSubmitting] = useState(false), [error, setError] = useState(''), [, render] = useState(0);
  React.useEffect(() => { for (const p of type.properties) if (!dirty.current.has(p.key)) values.current[p.key] = p.kind === 'json' ? JSON.stringify(block.data[p.key] ?? null, null, 2) : block.data[p.key] ?? ''; render(n => n + 1); }, [block.data]);
  const save = async (p: BlockType['properties'][number], raw: unknown) => {
    const value = propertyValue(p.kind, raw); const result = await c.edit([{ type: 'block.update', id: block.id, patch: { data: { [p.key]: value } } }], `Editar «${p.label}»`); if (result) dirty.current.delete(p.key); return result;
  };
  return <View style={{ gap: 8 }}>{type.properties.map(p => p.kind === 'boolean' ? <CheckRow key={p.key} label={p.label} checked={values.current[p.key] === true} disabled={c.offline || submitting} onPress={() => { const checked = values.current[p.key] !== true; values.current[p.key] = checked; dirty.current.add(p.key); render(n => n + 1); void save(p, checked).catch(e => setError(String(e))); }} /> : <Field key={p.key} label={p.label} required={p.required} value={p.kind === 'json' ? JSON.stringify(block.data[p.key] ?? null, null, 2) : str(block.data[p.key])} disabled={c.offline || submitting} multiline={p.kind === 'json'} mono={p.kind !== 'text'} onDraft={value => { values.current[p.key] = value; dirty.current.add(p.key); }} onSave={value => save(p, value)} />)}{error && <Txt kind="small">{error}</Txt>}<Button label={submitting ? 'Enviando…' : 'Enviar'} variant="primary" small disabled={c.offline || submitting} onPress={() => { void (async () => { setSubmitting(true); setError(''); try { const documentId = c.current.current?.document.id; await c.settle(); if (documentId !== c.current.current?.document.id) return; const data = Object.fromEntries(type.properties.map(p => [p.key, propertyValue(p.kind, values.current[p.key])])) as CanvasBlock['data']; const result = await c.edit([{ type: 'block.update', id: block.id, patch: { data } }], `Guardar formulario «${block.title}»`); if (!result) throw new Error('No se guardó el formulario.'); const committed = result.document.blocks.find(b => b.id === block.id); if (committed) await submit(committed.data); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setSubmitting(false); } })(); }} /></View>;
}
function Media({ block }: { block: CanvasBlock }) {
  const u = useUI(), toast = useToast(), url = safeUrl(block.data.url), [failed, setFailed] = useState(false);
  React.useEffect(() => setFailed(false), [url]);
  if (!url) return <Txt kind="small" style={{ color: u.c.statusDanger }}>Enlace no válido</Txt>;
  const kind = str(block.data.mediaKind), icon = tokens.media.kinds[kind as keyof typeof tokens.media.kinds] ?? 'Link';
  return <View style={{ gap: 8 }}>{kind === 'image' && !failed ? <Image source={{ uri: url }} accessibilityLabel={str(block.data.caption) || block.title} onError={() => setFailed(true)} resizeMode="contain" style={{ height: 180, backgroundColor: u.c.surface2, borderRadius: 6 }} /> : <View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><Icon name={icon} size={20} color={u.tone('turquesa')} /><View style={{ flex: 1 }}><Txt kind="bodyStrong">{new URL(url).hostname}</Txt><Txt kind="code" muted selectable numberOfLines={1}>{url}</Txt></View></View>}<Button label="Abrir referencia" small variant="ghost" icon="ExternalLink" onPress={() => { void openExternalUrl(url).catch(e => toast.error(String(e))); }} />{block.data.caption && <Txt kind="small" muted>{str(block.data.caption)}</Txt>}</View>;
}
export function BlockCard({ block, controller: c, selected, onSelect, onInspect, onPacks, onReorder, headerHandlers, onMeasure, outline = false, dragging = false }: { block: CanvasBlock; controller: CanvasController; selected: boolean; onSelect: (id: string, event?: GestureResponderEvent, multi?: boolean) => void; onInspect: () => void; onPacks: () => void; onReorder: (id: string, direction: number) => void; headerHandlers?: object; onMeasure?: (height: number) => void; outline?: boolean; dragging?: boolean }) {
  const u = useUI(), toast = useToast(), type = c.catalog?.blockTypes.find(t => t.id === block.typeId), v = visual(type), [menu, setMenu] = useState(false), [focus, setFocus] = useState(false), [hovered, setHovered] = useState(false), [answer, setAnswer] = useState(str(block.data.answer)), [hint, setHint] = useState(false), [sending, setSending] = useState(false), [sendError, setSendError] = useState('');
  const retry = useRef<null | { action: RpcInput<typeof agentAction>['action']; id: string }>(null);
  React.useEffect(() => setAnswer(str(block.data.answer)), [block.data.answer]);
  const pending = c.pendingIds.includes(block.id), writeFailure = c.failure?.affectedIds?.includes(block.id) ? c.failure : null;
  const disabled = pending || c.offline;
  const event = [...c.events].reverse().find(e => e.action.targetIds?.includes(block.id));
  async function send(kind: string, payload: CanvasBlock['data'], label: string, delivery: 'immediate' | 'batched' = 'immediate', again = false) {
    if (sending) return;
    if (!again) retry.current = { action: { kind, label, payload, targetIds: [block.id], delivery }, id: newId('evt') };
    setSending(true); setSendError('');
    try { const request = retry.current!; const result = await c.send(request.action, request.id); if (!result) setSendError('No se envió. Revisa el aviso del lienzo.'); else if (result.status === 'failed') setSendError(result.error ?? 'No se envió'); }
    finally { setSending(false); }
  }
  const retrySend = () => { if (event?.status === 'failed') { void c.task(async () => { const result = await c.api.flush({ workspaceId: c.workspaceId, documentId: c.view!.document.id }); c.setEvents(result.events); }); } else if (retry.current) void send('', {}, '', 'immediate', true); };
  const fieldSave = (key: string, value: unknown) => c.edit([{ type: 'block.update', id: block.id, patch: { data: { [key]: value } as CanvasBlock['data'] } }], `Editar «${key}»`);
  const generic = () => <View style={{ gap: 8 }}>{(type?.properties ?? Object.keys(block.data).map(key => ({ key, label: key, kind: 'json' }))).map(p => <View key={p.key} style={{ gap: 4 }}><Txt kind="label" muted>{p.label}</Txt><Txt kind={p.kind === 'json' || p.kind === 'number' ? 'code' : 'body'} selectable numberOfLines={outline ? undefined : p.kind === 'json' ? 4 : 8}>{typeof block.data[p.key] === 'boolean' ? block.data[p.key] ? 'Sí' : 'No' : str(block.data[p.key])}</Txt></View>)}</View>;
  let body: React.ReactNode = generic(), qualifier = '';
  const renderer = type?.renderer;
  if (!type) body = <View style={{ gap: 8 }}><Txt>Este tipo no está en tu catálogo. Importa el pack que lo define.</Txt><Button label="Abrir packs" small variant="ghost" onPress={onPacks} /></View>;
  else if (['note', 'text', 'callout', 'step'].includes(renderer ?? '') && typeof block.data.text === 'string') body = <Txt selectable numberOfLines={outline ? undefined : 8}>{block.data.text}</Txt>;
  else if (renderer === 'code' && typeof block.data.code === 'string') {
    const lines = block.data.code.split('\n'); qualifier = str(block.data.language);
    body = <View style={{ gap: 4, backgroundColor: u.c.surface2, borderRadius: 6, padding: 8 }}><View style={{ position: 'absolute', right: 0, top: 0, zIndex: 1 }}><IconButton label="Copiar código" icon="Copy" onPress={() => { void copyText(str(block.data.code)).then(() => toast.show('Código copiado')).catch(() => toast.error('Selecciona el código para copiarlo.')); }} /></View><ScrollView horizontal><Txt kind="code" selectable>{(outline ? lines : lines.slice(0, 12)).join('\n')}</Txt></ScrollView>{!outline && lines.length > 12 && <Txt kind="label" muted>… {lines.length - 12} líneas más</Txt>}</View>;
  } else if (renderer === 'checklist' && Array.isArray(block.data.items)) {
    const items = block.data.items.map(item => typeof item === 'string' ? { label: item, done: false } : { label: str((item as { label?: unknown })?.label), done: !!(item as { done?: unknown })?.done }); qualifier = `${items.filter(i => i.done).length}/${items.length}`;
    body = <View>{items.map((item, i) => <CheckRow key={i} label={item.label} checked={item.done} tone="exito" strike={item.done} disabled={disabled} onPress={() => { void fieldSave('items', items.map((old, index) => index === i ? { ...old, done: !old.done } : old)); }} />)}</View>;
  } else if ((renderer === 'choice' || renderer === 'quiz') && Array.isArray(block.data.options)) {
    qualifier = `${block.data.options.length} opciones`;
    body = <View style={{ gap: 8 }}><Txt>{str(block.data.question)}</Txt>{block.data.options.map((option, i) => <OptionRow key={i} label={str(option)} selected={answer === str(option)} disabled={c.offline || sending} onPress={() => setAnswer(str(option))} />)}<Button label={sending ? 'Enviando…' : 'Enviar respuesta'} variant="primary" small disabled={disabled || sending || !answer || answer === block.data.answer} onPress={() => { void (async () => { const result = await fieldSave('answer', answer); if (result) await send('block.answer', { answer }, `Responder «${block.title}»`); })(); }} />{renderer === 'quiz' && block.data.hint && <><Button label="Ver pista" small variant="ghost" disabled={disabled || hint} onPress={() => { setHint(true); void send('block.hint', {}, `Ver pista de «${block.title}»`, 'batched'); }} />{hint && <View style={{ backgroundColor: u.wash('turquesa'), padding: 8, borderRadius: 6 }}><Txt>{str(block.data.hint)}</Txt></View>}</>}{block.data.answer && block.data.explanation && <Txt>{str(block.data.explanation)}</Txt>}</View>;
  } else if (renderer === 'progress') {
    const total = Number(block.data.total), current = Math.max(0, Math.min(Number(block.data.current) || 0, total));
    body = <View style={{ gap: 6 }}><View accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: Math.max(0, total), now: current }} style={{ height: 6, backgroundColor: u.c.surface2, borderRadius: 3, overflow: 'hidden' }}><View style={{ width: `${total > 0 ? current / total * 100 : 0}%`, height: 6, backgroundColor: u.tone('exito') }} /></View><Txt kind="small" muted>{total > 0 ? `${current} de ${total}` : 'Sin total'}</Txt></View>;
  } else if (renderer === 'preview-frame') { qualifier = safeUrl(block.data.url) ? 'En vivo' : ''; body = <UrlPreview block={block} selected={selected} select={() => onSelect(block.id)} />; }
  else if (renderer === 'image-ref') body = <Media block={block} />;
  else if (renderer === 'diagram') { qualifier = `${Array.isArray(block.data.nodes) ? block.data.nodes.length : 0} nodos`; body = <Diagram block={block} disabled={disabled || sending} onAsk={(nodeId, label) => { void send('diagram.step', { nodeId, label }, `Preguntar por «${label}»`); }} />; }
  else if (renderer === 'metric') body = <View><Txt kind="display">{str(block.data.value)} {str(block.data.unit)}</Txt><Txt kind="small" muted>{str(block.data.label)}</Txt></View>;
  else if (renderer === 'form') body = <FormBody block={block} type={type} controller={c} submit={values => send('block.submit', { values }, `Enviar «${block.title}»`)} />;
  const actions = <View style={{ gap: 4 }}><Button label="Inspeccionar" small variant="ghost" onPress={onInspect} /><Button label="Duplicar" small icon="CopyPlus" disabled={disabled} onPress={() => { setMenu(false); void c.edit([{ type: 'entity.duplicate', id: block.id, idPrefix: newId('copy') }], 'Duplicar bloque'); }} />{block.parentGroupId && <><Button label="Subir" small disabled={disabled} onPress={() => onReorder(block.id, -1)} /><Button label="Bajar" small disabled={disabled} onPress={() => onReorder(block.id, 1)} /></>}<Button label="Eliminar" small variant="danger" disabled={disabled} onPress={() => { void c.edit([{ type: 'block.delete', id: block.id }], 'Eliminar bloque'); }} /></View>;
  return <View onLayout={e => onMeasure?.(e.nativeEvent.layout.height)} style={{ opacity: dragging ? .92 : pending ? .7 : 1 }}>
    {(selected || focus) && <View pointerEvents="none" style={{ position: 'absolute', top: -3, bottom: -3, left: -3, right: -3, borderRadius: 13, backgroundColor: selected ? u.halo : withAlpha(u.c.foregroundMuted, .3) }} />}<View style={{ backgroundColor: u.c.surface1, borderWidth: selected ? 2 : 1, borderColor: writeFailure ? u.c.statusDanger : selected ? u.c.accent : hovered ? withAlpha(u.c.foregroundMuted, .5) : u.c.border, borderRadius: 10, overflow: 'hidden', padding: selected ? 11 : 12, paddingLeft: selected ? 14 : 15, gap: 6, minHeight: 72 }}><View style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: 3, backgroundColor: v.tone === 'neutro' ? u.c.border : u.tone(v.tone as Tone) }} />
      <Pressable {...headerHandlers} accessibilityRole="button" accessibilityLabel={`${type?.name ?? block.typeId}: ${block.title}`} onHoverIn={() => setHovered(true)} onHoverOut={() => setHovered(false)} onFocus={() => setFocus(true)} onBlur={() => setFocus(false)} onPress={e => onSelect(block.id, e)} onLongPress={e => onSelect(block.id, e, true)} style={{ minHeight: u.compact ? 24 : 16, flexDirection: 'row', gap: 6, alignItems: 'center' }}><Icon name={v.icon} size={14} color={u.tone(v.tone as Tone)} /><Txt kind="label" muted numberOfLines={1} style={{ flex: 1 }}>{type?.name ?? block.typeId}{qualifier ? ` · ${qualifier}` : ''}</Txt>{c.view?.document.example && renderer === 'preview-frame' && <Chip label="Ejemplo" tone="aviso" icon="FlaskConical" />}{(selected || hovered) && <Pressable accessibilityRole="button" accessibilityLabel="Opciones del bloque" hitSlop={12} onPress={event => { event.stopPropagation(); onSelect(block.id); setMenu(!menu); }} style={{ width: 20, height: 20, alignItems: 'center', justifyContent: 'center' }}><Icon name="Ellipsis" size={14} color={u.c.foregroundMuted} /></Pressable>}</Pressable>
      {!!block.title && <Pressable onPress={e => onSelect(block.id, e)}><Txt kind="heading" numberOfLines={outline ? undefined : 3}>{block.title}</Txt></Pressable>}
      {menu && !u.compact && actions}{body}{(hasCommunication(block.communication) || pending || writeFailure || sending || sendError || event) && <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 4, alignItems: 'center' }}>{hasCommunication(block.communication) && <Chip label="Con instrucción" tone="acento" icon="Compass" />}{pending ? <Txt kind="small" muted>Guardando…</Txt> : writeFailure ? <View><Txt kind="small" style={{ color: u.c.statusDanger }}>No se guardó</Txt>{writeFailure.retry && <Button label="Reintentar" small variant="ghost" onPress={() => { void writeFailure.retry?.().catch(e => c.fail(e)); }} />}</View> : sending ? <Txt kind="small" muted>Enviando…</Txt> : sendError ? <View><Txt kind="small" style={{ color: u.c.statusDanger }}>{sendError}</Txt><Button label="Reintentar" small variant="ghost" onPress={retrySend} /></View> : <Delivery event={event} retry={retrySend} />}</View>}
    </View>{u.compact && <Modal title="Opciones del bloque" open={menu} onOpenChange={setMenu}><Modal.Content>{actions}</Modal.Content></Modal>}
  </View>;
}
