import React, { useState } from 'react';
import { Pressable, View } from 'react-native';
import { Icon, ScrollView, useToast } from '@getpaseo/plugin/client/react-native';
import { blockTypeSchema, type BlockType, type CanvasPack } from '../shared/model';
import type { CanvasController } from './useCanvas';
import { Modal, Button, CheckRow, Chip, Input, JsonPreview, Segments, Txt, friendlyError, useUI } from './ui';
import { forkPack, newId } from './logic';
import { pickJsonFile } from './web';
import { visual } from './Blocks';
import { withAlpha, type Tone } from './color';
import { getClientRenderer } from './renderers';
import { isWhiteboardRenderer } from '../shared/whiteboard';
export function Catalog({ controller: c, insert, insertTemplate, onImport, onExport, searchRef, initialTab, extras = [] }: { controller: CanvasController; insert: (type: BlockType) => void; insertTemplate: (id: string) => void; onImport: () => void; onExport: (pack: CanvasPack) => void; searchRef?: React.RefObject<View | null>; initialTab?: 'types' | 'templates' | 'packs'; extras?: { label: string; icon: string; onPress: () => void }[] }) {
  const u = useUI(), [tab, setTab] = useState<'types' | 'templates' | 'packs'>(initialTab ?? 'types'), [search, setSearch] = useState(''), [editor, setEditor] = useState(false), [json, setJson] = useState(''), [error, setError] = useState('');
  React.useEffect(() => { if (initialTab) setTab(initialTab); }, [initialTab]);
  const matches = (name: string, id: string) => `${name} ${id}`.toLowerCase().includes(search.toLowerCase()), disabled = c.busy || c.offline;
  const list = tab === 'types' ? c.catalog?.blockTypes : tab === 'templates' ? c.catalog?.templates : c.catalog?.packs;
  // The picker shows names only, grouped by what a block is for; the description of the hovered one sits in the footer.
  type Item = { key: string; name: string; label: string; description: string; icon: string; tone: Tone; onPress: () => void };
  const [hint, setHint] = useState<Item | null>(null);
  const typeItems = (c.catalog?.blockTypes ?? []).filter(t => matches(t.name, t.id)).map((type): Item & { section: number } => { const v = visual(type); return { key: type.id, name: type.name, label: `Añadir ${type.name}`, description: type.description, icon: v.icon, tone: v.tone as Tone, onPress: () => insert(type), section: isWhiteboardRenderer(type.renderer) ? 2 : getClientRenderer(type.renderer) ? 1 : 0 }; });
  const extraItems = extras.filter(e => matches(e.label, '')).map((e): Item => ({ key: e.label, name: e.label.replace('…', ''), label: e.label, description: '', icon: e.icon, tone: 'neutro', onPress: e.onPress }));
  const sections = [{ title: 'Básicos', items: [...typeItems.filter(i => i.section === 0), ...extraItems] }, { title: 'Interactivos', items: typeItems.filter(i => i.section === 1) }, { title: 'Pizarra', items: typeItems.filter(i => i.section === 2) }].filter(section => section.items.length);
  return <View style={{ flex: 1, minHeight: 0, backgroundColor: u.c.surface1 }}><View style={{ padding: 12, gap: 8 }}><View ref={searchRef}><Input value={search} onChange={setSearch} placeholder="Buscar" /></View><Segments value={tab} options={[{ value: 'types', label: 'Bloques' }, { value: 'templates', label: 'Plantillas' }, { value: 'packs', label: 'Colecciones' }]} onChange={setTab} />{tab === 'packs' && <Button label="Importar colección" icon="FileInput" onPress={onImport} disabled={disabled} />}</View><ScrollView contentContainerStyle={{ padding: 12, paddingTop: 0, gap: 8 }}>
    {!c.catalog && <Txt muted>Cargando catálogo…</Txt>}
    {tab === 'types' && sections.map(section => <View key={section.title} style={{ gap: 4 }}>
      <Txt kind="label" muted style={{ paddingHorizontal: 4, paddingTop: 6 }}>{section.title}</Txt>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>{section.items.map(item => <Pressable key={item.key} accessibilityRole="button" accessibilityLabel={item.label} accessibilityHint={item.description} disabled={disabled} onPress={item.onPress} onHoverIn={() => setHint(item)} onHoverOut={() => setHint(current => current === item ? null : current)}
        style={({ pressed, ...state }) => ({ width: u.compact ? '100%' : '50%', minHeight: u.compact ? 44 : 40, paddingHorizontal: 4, borderRadius: 8, flexDirection: 'row', alignItems: 'center', gap: 10, opacity: disabled ? .45 : 1, backgroundColor: pressed ? withAlpha(u.c.foreground, .1) : (state as { hovered?: boolean }).hovered ? withAlpha(u.c.foreground, .06) : 'transparent' })}>
        <View style={{ width: 28, height: 28, borderRadius: 6, backgroundColor: u.wash(item.tone), alignItems: 'center', justifyContent: 'center' }}><Icon name={item.icon} size={16} color={u.tone(item.tone)} /></View><Txt numberOfLines={1} style={{ flex: 1 }}>{item.name}</Txt>
      </Pressable>)}</View>
    </View>)}
    {tab === 'templates' && c.catalog?.templates.filter(t => matches(t.name, t.id)).map(template => <Pressable key={template.id} accessibilityRole="button" accessibilityLabel={`Añadir plantilla ${template.name}`} disabled={disabled} onPress={() => insertTemplate(template.id)} style={{ borderRadius: 10, borderWidth: 1, borderColor: u.c.border, backgroundColor: u.c.surface0, padding: 12, gap: 8, opacity: disabled ? .45 : 1 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ width: 56, height: 40, borderRadius: 6, borderWidth: 1.5, borderColor: u.c.border, padding: 6, gap: 4 }}>{template.blocks.slice(0, 3).map(b => <View key={b.id} style={{ height: 4, borderRadius: 2, backgroundColor: u.washStrong(visual(c.catalog?.blockTypes.find(t => t.id === b.typeId)).tone as Tone) }} />)}</View><Txt kind="bodyStrong" style={{ flex: 1 }}>{template.name}</Txt></View><Txt kind="small" muted>{template.description}</Txt><Txt kind="label" muted>{template.blocks.length} bloques · {template.groups.length} grupos</Txt></Pressable>)}
    {tab === 'packs' && c.catalog?.packs.filter(p => matches(p.name, p.id)).map(pack => <View key={pack.id} style={{ borderRadius: 10, borderWidth: 1, borderColor: u.c.border, backgroundColor: u.c.surface0, padding: 12, gap: 8 }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}><Icon name="Package" size={16} color={u.c.foregroundMuted} /><Txt kind="bodyStrong" style={{ flex: 1 }}>{pack.name}</Txt>{['frontend', 'learn'].includes(pack.id) && <Chip label="Ejemplo" tone="aviso" icon="FlaskConical" />}</View>
      <Txt kind="small" muted>{pack.description}</Txt><Txt kind="label" muted>{pack.blockTypes.length} tipos · {pack.templates.length} plantillas · {pack.documents.length} documentos</Txt>
      {pack.documents.map((doc, i) => <View key={i} style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Txt kind="small" style={{ flex: 1 }}>{doc.title}</Txt><Button label="Crear documento" small variant="ghost" disabled={disabled} onPress={() => { void c.example(pack.id, i); }} /></View>)}
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Button label="Exportar" small variant="ghost" icon="FileOutput" disabled={disabled} onPress={() => { void c.task(async () => onExport(await c.api.export({ id: pack.id }))); }} />{!['frontend', 'learn'].includes(pack.id) && <Button label="Quitar" small variant="danger" disabled={disabled} style={{ borderColor: 'transparent' }} onPress={() => { void c.task(async () => { c.setCatalog(await c.api.catalogMutate({ expectedRevision: c.catalog!.revision, action: { type: 'pack.remove', id: pack.id } })); }); }} />}</View>
    </View>)}
    {tab === 'types' && <Button label="Crear tipo de bloque" small variant="ghost" icon="Plus" disabled={disabled} onPress={() => { setJson(JSON.stringify({ id: newId('type'), name: 'Nuevo tipo', description: '', properties: [{ key: 'text', label: 'Texto', kind: 'text', required: false }], defaults: { text: '' }, renderer: 'note' }, null, 2)); setEditor(true); }} />}
    {list && !list.some(t => matches(t.name, t.id)) && !(tab === 'types' && sections.length) && <><Txt kind="small" muted>Nada coincide con «{search}».</Txt><Button label="Limpiar búsqueda" variant="ghost" onPress={() => setSearch('')} /></>}
  </ScrollView>{tab === 'types' && !u.compact && <View style={{ minHeight: 36, paddingHorizontal: 16, paddingVertical: 8, borderTopWidth: 1, borderColor: u.c.border, justifyContent: 'center' }}><Txt kind="small" muted numberOfLines={2}>{hint?.description || 'Pasa el cursor por un bloque para ver qué hace.'}</Txt></View>}<Modal title="Crear tipo de bloque" open={editor} onOpenChange={setEditor}><Modal.Content><Txt kind="small" muted>Define propiedades y valores iniciales. El catálogo guarda datos declarativos.</Txt><Input value={json} onChange={setJson} multiline mono style={{ minHeight: 220 }} />{error && <Txt kind="small" style={{ color: u.c.statusDanger }}>{error}</Txt>}<Button label="Guardar tipo" variant="primary" disabled={disabled} onPress={() => { void (async () => { try { const blockType = blockTypeSchema.parse(JSON.parse(json)); const result = await c.task(async () => { const catalog = await c.api.catalogMutate({ expectedRevision: c.catalog!.revision, action: { type: 'type.put', blockType } }); c.setCatalog(catalog); return catalog; }); if (result) setEditor(false); else setError('No se guardó. Revisa el aviso del lienzo.'); } catch (e) { setError(friendlyError(e)); } })(); }} /></Modal.Content></Modal></View>;
}
export function PackImport({ controller: c, open, close }: { controller: CanvasController; open: boolean; close: () => void }) {
  const u = useUI(), toast = useToast(), [text, setText] = useState(''), [issues, setIssues] = useState<string[]>([]), [replace, setReplace] = useState(false), [review, setReview] = useState<{ pack: CanvasPack; revision: number; diff: { added: string[]; replaced: string[]; unchanged: string[] } } | null>(null), [pending, setPending] = useState(false);
  const change = (value: string) => { setText(value); setReview(null); setIssues([]); };
  async function check() {
    setPending(true); setIssues([]); setReview(null);
    try {
      const pack = JSON.parse(text) as CanvasPack, valid = await c.api.validate({ pack }); if (!valid.valid) { setIssues([...new Set(valid.issues.map(friendlyError))]); return; }
      const cat = await c.api.catalog({}); c.setCatalog(cat);
      // A dry run never writes; replace:true is necessary to inspect an existing pack's diff.
      const result = await c.api.import({ pack, expectedRevision: cat.revision, replace: true, dryRun: true });
      setReview({ pack, revision: cat.revision, diff: result.diff });
    } catch (e) { setIssues([friendlyError(e)]); }
    finally { setPending(false); }
  }
  return <Modal title="Importar colección" open={open} onOpenChange={v => { if (!v) close(); }}><Modal.Content>{u.layout.platform === 'web' && <Button label="Elegir archivo…" small icon="FolderOpen" disabled={pending} onPress={() => { void pickJsonFile().then(value => { if (value !== null) change(value); }).catch(e => toast.error(friendlyError(e))); }} />}<Input value={text} onChange={change} multiline mono placeholder='{ "format": "paseo-canvas-pack", "version": 1, … }' style={{ minHeight: review ? 64 : 160, maxHeight: review ? 96 : 300 }} /><Txt kind="small" muted>Pega el JSON de la colección. Se guarda solo en este equipo.</Txt><Button label={pending ? 'Revisando…' : 'Revisar'} disabled={pending || !text} onPress={() => { void check(); }} />{issues.length > 0 && <View style={{ backgroundColor: u.wash('riesgo'), borderRadius: 6, padding: 10, gap: 6 }}><Txt kind="bodyStrong">No es una colección válida</Txt>{issues.slice(0, 6).map((s, i) => <Txt key={i} kind="small">{s}</Txt>)}{issues.length > 6 && <Txt kind="small" muted>y {issues.length - 6} más</Txt>}</View>}{review && <View style={{ gap: 8 }}><Txt kind="title">{review.pack.name}</Txt><ScrollView style={{ maxHeight: 220 }} contentContainerStyle={{ gap: 6 }}>{(['added', 'replaced'] as const).map(kind => review.diff[kind].map(id => <View key={`${kind}:${id}`} style={{ flexDirection: 'row', gap: 6 }}><Icon name={kind === 'added' ? 'Plus' : 'RotateCw'} size={14} color={kind === 'added' ? u.c.statusSuccess : u.c.statusWarning} /><Txt kind="small" selectable style={{ flex: 1 }}>{kind === 'added' ? 'Nuevo' : 'Reemplaza'}: {review.pack.blockTypes.find(t => t.id === id)?.name ?? review.pack.templates.find(t => t.id === id)?.name ?? 'Contenido de la colección'}</Txt></View>))}</ScrollView>{review.diff.unchanged.length > 0 && <Txt kind="small" muted>y {review.diff.unchanged.length} sin cambios</Txt>}{c.catalog?.packs.some(p => p.id === review.pack.id) && <View style={{ gap: 4 }}><CheckRow label="Reemplazar los que ya existen" checked={replace} onPress={() => { setReplace(!replace); }} />{!replace && <Txt kind="small" muted>Esta colección ya está instalada. Marca «Reemplazar los que ya existen» para continuar.</Txt>}</View>}<Button label="Importar colección" variant="primary" disabled={pending || c.offline || (!replace && !!c.catalog?.packs.some(p => p.id === review.pack.id))} onPress={() => { void (async () => { setPending(true); try { const result = await c.api.import({ pack: review.pack, expectedRevision: review.revision, replace, dryRun: false }); if (result.committed) { c.setCatalog(result.catalog); toast.show(`Colección «${review.pack.name}» importada`, { variant: 'success' }); close(); } } catch (e) { setIssues([friendlyError(e)]); setReview(null); } finally { setPending(false); } })(); }} /></View>}</Modal.Content></Modal>;
}
export function PackExport({ pack, close }: { pack: CanvasPack | null; close: () => void }) {
  const u = useUI(), [portable, setPortable] = useState<CanvasPack | null>(null), [mode, setMode] = useState<'portable' | 'reference'>('portable');
  React.useEffect(() => { setMode('portable'); setPortable(pack && ['frontend', 'learn'].includes(pack.id) ? forkPack(pack) : pack); }, [pack]);
  const exported = mode === 'reference' ? pack : portable;
  return <Modal title="Exportar colección" open={!!pack} onOpenChange={v => { if (!v) close(); }}><Modal.Content>{pack && <><Txt kind="title">{pack.name}</Txt>{['frontend', 'learn'].includes(pack.id) && <><Segments value={mode} options={[{ value: 'portable', label: 'Copia portable' }, { value: 'reference', label: 'Referencia' }]} onChange={setMode} /><View style={{ padding: 12, borderRadius: 6, backgroundColor: u.wash('aviso') }}><Txt kind="small">{mode === 'portable' ? 'El ejemplo integrado está protegido. Esta copia portable tiene sus propios tipos y plantillas; puedes importarla sin reemplazar el original.' : 'Referencia protegida. Este JSON no puede importarse directamente. Elige Copia portable para obtener una colección importable.'}</Txt></View></>}{exported && <JsonPreview value={exported} filename={`${exported.id}.lienzo-pack.json`} />}</>}</Modal.Content></Modal>;
}
