import React, { useEffect, useRef, useState } from 'react';
import { Pressable, View } from 'react-native';
import { Icon, ScrollView } from '@getpaseo/plugin/client/react-native';
import { diagramDataSchema, type CanvasBlock } from '../shared/model';
import { diagramLayout } from './logic';
import { tokens } from './tokens';
import { withAlpha } from './color';
import { keyboard } from './web';
import { Button, IconButton, Segments, Txt, useUI } from './ui';
export function Diagram({ block, onAsk, disabled }: { block: CanvasBlock; onAsk: (nodeId: string, label: string) => void; disabled: boolean }) {
  const u = useUI(), parsed = diagramDataSchema.safeParse(block.data), [width, setWidth] = useState(565), [step, setStep] = useState<string | null>(null), [mode, setMode] = useState<'all' | 'steps'>('all');
  const previous = useRef<string[] | null>(null), data = parsed.success ? parsed.data : { nodes: [], edges: [] };
  const root = useRef<View>(null);
  useEffect(() => { const ids = data.nodes.map(n => n.id); if (previous.current) { const added = ids.filter(id => !previous.current!.includes(id)); if (added.length) setStep(added.at(-1)!); else if (step && !ids.includes(step)) setStep(null); } previous.current = ids; }, [JSON.stringify(data.nodes.map(n => n.id))]);
  useEffect(() => { if (u.layout.platform !== 'web') return; return keyboard(root.current, e => { if (e.command || !data.nodes.length) return false; const i = data.nodes.findIndex(n => n.id === step); if (e.key === 'ArrowRight') { setStep(data.nodes[Math.min(data.nodes.length - 1, i + 1)].id); return true; } if (e.key === 'ArrowLeft') { setStep(data.nodes[Math.max(0, i - 1)].id); return true; } return false; }); }, [step, data.nodes, u.layout.platform]);
  if (!parsed.success) return <View style={{ gap: 8 }}><Txt>Datos de diagrama no válidos</Txt><Txt kind="code" selectable muted numberOfLines={4}>{JSON.stringify(block.data, null, 2)}</Txt></View>;
  const d = tokens.diagram, layout = diagramLayout(data, width), index = data.nodes.findIndex(n => n.id === step), current = data.nodes[index];
  const ghost = (id: string) => mode === 'steps' && data.nodes.findIndex(n => n.id === id) > index;
  const outgoing = (id: string) => data.edges.filter(e => e.from === id).map(e => <View key={e.id} style={{ flexDirection: 'row', gap: 4, alignItems: 'center' }}><Icon name="CornerDownRight" size={12} color={u.c.foregroundMuted} /><Txt kind="small" muted style={{ flex: 1 }}>{e.label ?? 'Sigue'} → {data.nodes.find(n => n.id === e.to)?.label}</Txt></View>);
  return <View ref={root} onLayout={e => setWidth(e.nativeEvent.layout.width)} style={{ gap: 8 }}>
    {!data.nodes.length ? <View style={{ minHeight: 96, borderWidth: 1, borderStyle: 'dashed', borderColor: u.c.border, borderRadius: 6, padding: 12, justifyContent: 'center' }}><Txt kind="small" muted>Diagrama vacío. El agente puede añadir nodos paso a paso.</Txt></View> : layout.list || u.compact ? <View style={{ gap: 10 }}>{data.nodes.map((node, i) => <Pressable key={node.id} accessibilityRole="button" accessibilityLabel={`Nodo ${i + 1} de ${data.nodes.length}: ${node.label}`} onPress={() => setStep(node.id)} style={{ flexDirection: 'row', gap: 8, paddingVertical: 6, paddingHorizontal: 8, borderRadius: 6, backgroundColor: step === node.id ? u.wash('acento') : 'transparent', opacity: ghost(node.id) ? .5 : 1 }}>
      <View style={{ width: 24, alignItems: 'center' }}><View style={{ width: 18, height: 18, borderRadius: 9, borderWidth: 1.5, borderColor: u.c.border, backgroundColor: step === node.id ? u.c.accent : u.c.surface0, alignItems: 'center' }}><Txt kind="label" style={{ color: step === node.id ? u.c.accentForeground : u.c.foregroundMuted }}>{i + 1}</Txt></View>{i < data.nodes.length - 1 && <View pointerEvents="none" style={{ position: 'absolute', top: 18, bottom: -22, width: 1.5, backgroundColor: withAlpha(u.c.foregroundMuted, .7) }} />}</View>
      <View style={{ flex: 1, gap: 4 }}><Txt kind="bodyStrong">{ghost(node.id) ? `Paso ${i + 1}` : node.label}</Txt>{!ghost(node.id) && <><Txt kind="small" muted numberOfLines={step === node.id ? undefined : 2}>{node.description}</Txt>{outgoing(node.id)}{step === node.id && <Button label="Preguntar por este paso" small variant="ghost" onPress={() => onAsk(node.id, node.label)} disabled={disabled} />}</>}</View>
    </Pressable>)}</View> : <ScrollView horizontal style={{ flexGrow: 0 }}><View style={{ width: layout.width, height: layout.height }}>
      {layout.edges.filter(e => !ghost(e.from) && !ghost(e.to)).map(edge => {
        const color = edge.to === step ? u.c.accent : withAlpha(u.c.foregroundMuted, .7), thickness = edge.to === step ? 2 : 1.5;
        return <React.Fragment key={edge.id}>{edge.segments.map((s, i) => {
          const horizontal = s.from.y === s.to.y;
          return <View key={i} pointerEvents="none" style={{ position: 'absolute', left: Math.min(s.from.x, s.to.x), top: Math.min(s.from.y, s.to.y), width: horizontal ? Math.abs(s.to.x - s.from.x) : edge.dashed ? 0 : thickness, height: horizontal ? edge.dashed ? 0 : thickness : Math.abs(s.to.y - s.from.y), backgroundColor: edge.dashed ? 'transparent' : color, borderStyle: edge.dashed ? 'dashed' : 'solid', borderColor: color, borderTopWidth: edge.dashed && horizontal ? thickness : 0, borderLeftWidth: edge.dashed && !horizontal ? thickness : 0 }} />;
        })}<View pointerEvents="none" style={{ position: 'absolute', left: edge.direction === 'right' ? edge.end.x - 7 : edge.direction === 'left' ? edge.end.x + 1 : edge.end.x - 3, top: edge.direction === 'down' ? edge.end.y - 7 : edge.direction === 'up' ? edge.end.y + 1 : edge.end.y - 3, width: 6, height: 6, borderRightWidth: 1.5, borderBottomWidth: 1.5, borderColor: color, transform: [{ rotate: edge.direction === 'down' ? '45deg' : edge.direction === 'right' ? '-45deg' : edge.direction === 'left' ? '135deg' : '225deg' }] }} />{edge.label && <View pointerEvents="none" style={{ position: 'absolute', left: edge.labelPoint.x - edge.labelWidth / 2, top: edge.labelPoint.y - 8, width: edge.labelWidth, alignItems: 'center' }}><Txt kind="small" numberOfLines={1} style={{ backgroundColor: u.c.surface1, paddingHorizontal: 4, paddingVertical: 1, borderRadius: 4, fontSize: 11, lineHeight: 14, maxWidth: edge.labelWidth, color: edge.to === step ? u.c.foreground : u.c.foregroundMuted }}>{edge.label}</Txt></View>}</React.Fragment>;
      })}
      {layout.nodes.map((node, i) => <Pressable key={node.id} accessibilityRole="button" accessibilityLabel={`Nodo ${i + 1} de ${data.nodes.length}: ${node.label}`} onPress={() => setStep(node.id)} style={{ position: 'absolute', left: node.x - 3, top: node.y - 3, width: node.width + 6, height: node.height + 6, padding: 3, borderRadius: 11, backgroundColor: step === node.id ? u.halo : 'transparent', opacity: ghost(node.id) ? d.ghost.opacity : 1 }}><View style={{ flex: 1, borderRadius: d.node.radius, borderWidth: step === node.id ? 2 : 1, borderStyle: ghost(node.id) ? 'dashed' : 'solid', borderColor: step === node.id ? u.c.accent : u.c.border, backgroundColor: ghost(node.id) ? 'transparent' : step === node.id ? u.c.surface1 : u.c.surface0, paddingHorizontal: 8, alignItems: 'center', justifyContent: 'center' }}>{!ghost(node.id) && <Txt kind="small" numberOfLines={2} style={{ fontWeight: '600', textAlign: 'center' }}>{node.label}</Txt>}</View></Pressable>)}
    </View></ScrollView>}
    {!!data.nodes.length && <View style={{ gap: 6, paddingTop: 6, borderTopWidth: 1, borderColor: u.c.border }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 4, marginLeft: -6 }}><IconButton icon="ChevronLeft" label="Paso anterior" disabled={index <= 0} onPress={() => setStep(data.nodes[index - 1].id)} /><Txt kind="label" muted numberOfLines={1} style={{ minWidth: 92, textAlign: 'center' }}>{index < 0 ? `${data.nodes.length} pasos` : `Paso ${index + 1} de ${data.nodes.length}`}</Txt><IconButton icon="ChevronRight" label="Paso siguiente" disabled={index === data.nodes.length - 1} onPress={() => setStep(data.nodes[index + 1].id)} /><View style={{ flex: 1 }} />{!layout.list && !u.compact && <View style={{ width: 184, marginLeft: 8 }}><Segments value={mode} options={[{ value: 'all', label: 'Todo' }, { value: 'steps', label: 'Paso a paso' }]} onChange={v => { setMode(v); if (v === 'steps' && index < 0) setStep(data.nodes[0].id); }} /></View>}</View>{(layout.list || u.compact) && <View style={{ width: 200 }}><Segments value={mode} options={[{ value: 'all', label: 'Todo' }, { value: 'steps', label: 'Paso a paso' }]} onChange={v => { setMode(v); if (v === 'steps' && index < 0) setStep(data.nodes[0].id); }} /></View>}</View>}
    {current && !layout.list && !u.compact && <View style={{ borderRadius: 6, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: u.wash('acento'), gap: 6 }}><Txt kind="label" muted>Paso {index + 1} de {data.nodes.length}</Txt><Txt kind="bodyStrong">{current.label}</Txt>{current.description && <Txt>{current.description}</Txt>}{outgoing(current.id)}<Button label="Preguntar por este paso" small style={{ alignSelf: 'flex-start' }} onPress={() => onAsk(current.id, current.label)} disabled={disabled} /></View>}
    {data.caption && <Txt kind="small" muted numberOfLines={3}>{data.caption}</Txt>}
  </View>;
}
