import React, { useEffect, useState } from 'react';
import { Pressable, View } from 'react-native';
import { Icon, ScrollView, copyText, useToast } from '@getpaseo/plugin/client/react-native';
import type { CanvasBlock, CanvasGroup, CanvasOperation } from '../shared/model';
import type { CanvasController } from './useCanvas';
import { Button, CheckRow, Chip, Field, IconButton, OptionRow, Section, Segments, Txt, useUI } from './ui';
import { hasCommunication, instructionLevels, newId, topSelection, ancestors } from './logic';
import { Delivery } from './Blocks';
type Communication = NonNullable<CanvasBlock['communication']>;
function CommunicationEditor({ value, save, scope, inherited, disabled, selectLevel, clear }: { value?: Communication; save: (v: Partial<Communication>) => Promise<unknown>; scope: string; inherited: { id: string; label: string; communication: Communication }[]; disabled: boolean; selectLevel: (id: string) => void; clear: () => Promise<unknown> }) {
  const u = useUI(), active = hasCommunication(value), [expanded, setExpanded] = useState(scope === 'Documento' || active), [clearing, setClearing] = useState(false);
  useEffect(() => setExpanded(scope === 'Documento' || active), [scope, active]);
  const effective = value ?? { intent: '', audience: '', instructions: '' };
  return <View style={{ gap: 8 }}>{!expanded ? <Button label="Añadir instrucción" small onPress={() => setExpanded(true)} /> : <View style={{ borderRadius: 10, borderWidth: 1, borderColor: u.toneBorder('acento'), backgroundColor: u.wash('acento'), padding: 12, gap: 12 }}><View style={{ flexDirection: 'row', gap: 6, alignItems: 'center' }}><Icon name="Compass" size={14} color={u.c.accent} /><Txt kind="bodyStrong" style={{ flex: 1 }}>Instrucción</Txt><Txt kind="label" muted>{scope}</Txt></View>
    <Field label="Intención" value={effective.intent} disabled={disabled} placeholder="Para qué se usa esto: enseñar, revisar, decidir…" onSave={intent => save({ intent })} />
    <Field label="Audiencia" value={effective.audience} disabled={disabled} placeholder="A quién le habla el agente" onSave={audience => save({ audience })} />
    <Field label="Instrucciones" value={effective.instructions} disabled={disabled} multiline counterMax={8000} placeholder="Cómo debe comunicarse el agente a través de este lienzo" onSave={instructions => save({ instructions })} />
    {scope !== 'Documento' && active && <Button label="Vaciar instrucción" icon="Eraser" small variant="ghost" disabled={disabled || clearing} onPress={() => { setExpanded(false); setClearing(true); void clear().then(result => { if (!result) setExpanded(true); }).catch(() => setExpanded(true)).finally(() => setClearing(false)); }} />}
  </View>}{inherited.length > 0 && <View style={{ gap: 4 }}><Txt kind="small" muted>También se aplican:</Txt>{inherited.map(level => <Pressable key={level.id} accessibilityRole="button" accessibilityLabel={`Editar instrucción: ${level.label}`} onPress={() => selectLevel(level.id)} style={{ gap: 4, minHeight: u.compact ? 44 : 36, paddingVertical: 6 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}><Icon name="Compass" size={12} color={u.c.accent} /><Txt kind="small" muted>{level.label}</Txt></View><Txt kind="small" muted numberOfLines={2}>{level.communication.instructions || level.communication.intent || level.communication.audience}</Txt></Pressable>)}</View>}</View>;
}
export function Inspector({ controller: c, onClose, groupSelection, reparent, onTemplate, onExportSelection, reorder, initialSection }: { controller: CanvasController; onClose?: () => void; groupSelection: () => void; reparent: (id: string, parent: string | null) => void; onTemplate: (g: CanvasGroup) => void; onExportSelection: () => void; reorder: (id: string, direction: number) => void; initialSection?: 'document' | 'communication' | 'history' | 'activity' }) {
  const u = useUI(), toast = useToast(), doc = c.view?.document, [history, setHistory] = useState<Awaited<ReturnType<typeof c.api.history>>['transactions']>([]);
  const scroller = React.useRef<React.ComponentRef<typeof ScrollView>>(null), anchors = React.useRef<Record<string, number>>({});
  const anchor = (section: string) => (event: { nativeEvent: { layout: { y: number } } }) => { anchors.current[section] = event.nativeEvent.layout.y; if (initialSection === section) scroller.current?.scrollTo({ y: event.nativeEvent.layout.y, animated: false }); };
  useEffect(() => { if (initialSection) scroller.current?.scrollTo({ y: anchors.current[initialSection] ?? 0, animated: false }); }, [initialSection]);
  useEffect(() => { let live = true; if (doc) void c.api.history({ workspaceId: c.workspaceId, documentId: doc.id }).then(r => { if (live) setHistory(r.transactions); }).catch(() => {}); return () => { live = false; }; }, [doc?.id, doc?.revision]);
  if (!doc) return <View style={{ padding: 16 }}><Txt muted>{c.loading ? 'Cargando…' : 'Abre un documento para editarlo.'}</Txt></View>;
  const selected = [...doc.groups, ...doc.blocks].filter(e => c.selection.includes(e.id)), e = selected.length === 1 ? selected[0] : undefined;
  const group = e && 'groupIds' in e ? e : undefined, block = e && 'typeId' in e ? e : undefined, type = c.catalog?.blockTypes.find(t => t.id === block?.typeId), disabled = c.busy || c.offline;
  const groupMode = group?.layout?.mode ?? (group && [...group.blockIds, ...group.groupIds].some(id => [...doc.blocks, ...doc.groups].find(item => item.id === id)?.position) ? 'free' : 'stack');
  const editEntity = (patch: Partial<CanvasBlock> | Partial<CanvasGroup>, label: string) => c.edit([{ type: group ? 'group.update' : 'block.update', id: e!.id, patch } as CanvasOperation], label);
  const editComm = async (patch: Partial<Communication>) => {
    const id = doc.id, entityId = e?.id; await c.settle(); const latest = c.current.current?.document;
    if (!latest || latest.id !== id) return undefined;
    const target = entityId ? [...latest.blocks, ...latest.groups].find(item => item.id === entityId) : undefined;
    if (entityId && !target) return undefined;
    const communication = { intent: '', audience: '', instructions: '', ...(target?.communication ?? (!entityId ? latest.communication : undefined)), ...patch };
    return entityId ? c.edit([{ type: group ? 'group.update' : 'block.update', id: entityId, patch: { communication } } as CanvasOperation], 'Editar instrucción') : c.edit([{ type: 'communication.set', communication }], 'Editar acuerdo de comunicación');
  };

  const clearComm = async () => {
    if (!e) return undefined;
    const id = doc.id, entityId = e.id; await c.settle(); const latest = c.current.current?.document;
    if (!latest || latest.id !== id || ![...latest.blocks, ...latest.groups].some(item => item.id === entityId)) return undefined;
    const result = await c.edit([{ type: group ? 'group.update' : 'block.update', id: entityId, patch: { communication: { intent: '', audience: '', instructions: '' } } }], 'Vaciar instrucción');
    if (result) toast.show('Instrucción vaciada', { variant: 'success' });
    return result;
  };

  return <View style={{ flex: 1, minHeight: 0, backgroundColor: u.c.surface1 }}><View style={{ minHeight: 48, padding: 12, borderBottomWidth: 1, borderColor: u.c.border, flexDirection: 'row', alignItems: 'center', gap: 8 }}><View style={{ flex: 1 }}><Txt kind="label" muted>{selected.length > 1 ? `${selected.length} seleccionados` : group ? 'Grupo' : block ? 'Bloque' : 'Documento'}</Txt><Txt kind="heading" numberOfLines={1}>{e?.title ?? doc.title}</Txt></View>{onClose && <IconButton label="Cerrar inspector" icon="X" onPress={onClose} />}</View><ScrollView ref={scroller} contentContainerStyle={{ padding: 16, gap: 20 }}>
    {selected.length > 1 ? <><View style={{ gap: 8 }}>{selected.map(item => <Button key={item.id} label={item.title || item.id} variant="ghost" onPress={() => { void c.select([item.id]); }} />)}</View><Button label="Agrupar" icon="Group" disabled={disabled} onPress={groupSelection} /><Button label="Eliminar" variant="danger" disabled={disabled} onPress={() => { void c.edit(topSelection(doc, c.selection).map(item => ({ type: 'groupIds' in item ? 'group.delete' : 'block.delete', id: item.id } as CanvasOperation)), 'Eliminar selección'); }} /></> : <>
      <View style={{ gap: 12 }}><Txt kind="label" muted>{group ? 'Grupo' : 'Contenido'}</Txt><Field label="Título" value={e?.title ?? doc.title} disabled={disabled} onSave={title => e ? editEntity({ title }, 'Editar título') : c.edit([{ type: 'document.update', title }], 'Editar título')} />
        {!block && <Field label={group ? 'Propósito' : 'Descripción'} value={group?.description ?? doc.description} multiline disabled={disabled} helper={group ? 'Una frase: para qué sirve este grupo.' : undefined} onSave={description => group ? editEntity({ description }, 'Editar propósito del grupo') : c.edit([{ type: 'document.update', description }], 'Editar descripción')} />}
        {!e && doc.example && <View style={{ backgroundColor: u.wash('aviso'), padding: 12, borderRadius: 6, gap: 8 }}><Chip label="Ejemplo" tone="aviso" icon="FlaskConical" /><Txt kind="small">Documento de ejemplo. Su contenido es ilustrativo y no proviene de tu agente.</Txt></View>}
        {block && type?.properties.map(p => p.kind === 'boolean' ? <CheckRow key={p.key} label={p.label} checked={!!block.data[p.key]} disabled={disabled} onPress={() => { void editEntity({ data: { [p.key]: !block.data[p.key] } }, `Editar «${p.key}»`); }} /> : <Field key={`${block.id}:${p.key}`} label={p.label} required={p.required} value={p.kind === 'json' ? JSON.stringify(block.data[p.key] ?? null, null, 2) : String(block.data[p.key] ?? '')} multiline={p.kind === 'json' || p.kind === 'text'} mono={p.kind !== 'text'} disabled={disabled} onSave={value => { let parsed: unknown = value; if (p.kind === 'json') { try { parsed = JSON.parse(value); } catch { throw new Error('JSON no válido'); } } else if (p.kind === 'number') { parsed = Number(value); if (!Number.isFinite(parsed)) throw new Error('Número no válido'); } return editEntity({ data: { [p.key]: parsed } as CanvasBlock['data'] }, `Editar «${p.key}»`); }} />)}
        {block && !type && <Txt kind="small" muted>Importa el pack que define este tipo para editar sus propiedades.</Txt>}
        {group && <><Txt kind="small">Disposición</Txt><Segments value={groupMode} options={(['stack', 'grid', 'flow', 'free'] as const).map(value => ({ value, label: tokensLabels[value] }))} onChange={mode => { void editEntity({ layout: { ...group.layout, mode } }, 'Cambiar disposición del grupo'); }} disabled={disabled} />{group.layout?.mode === 'grid' && <View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><IconButton icon="Minus" label="Menos columnas" disabled={disabled || (group.layout.columns ?? 2) <= 1} onPress={() => { void editEntity({ layout: { ...group.layout!, columns: (group.layout!.columns ?? 2) - 1 } }, 'Cambiar columnas'); }} /><Txt>{group.layout.columns ?? 2} columnas</Txt><IconButton icon="Plus" label="Más columnas" disabled={disabled || (group.layout.columns ?? 2) >= 4} onPress={() => { void editEntity({ layout: { ...group.layout!, columns: (group.layout!.columns ?? 2) + 1 } }, 'Cambiar columnas'); }} /></View>}<CheckRow label="Contraer grupo" checked={!!group.collapsed} disabled={disabled} onPress={() => { void editEntity({ collapsed: !group.collapsed }, 'Contraer grupo'); }} /></>}
      </View>
      {e && <Section title="Ubicación"><OptionRow label="Sin grupo" tone="acento" selected={!e.parentGroupId} disabled={disabled} onPress={() => reparent(e.id, null)} />{doc.groups.filter(g => g.id !== e.id && !ancestors(doc, g).some(parent => parent.id === e.id)).map(g => <OptionRow key={g.id} label={g.title || g.id} tone="acento" selected={e.parentGroupId === g.id} disabled={disabled} onPress={() => reparent(e.id, g.id)} />)}</Section>}
      {group && <Section title="Contenido">{[...group.blockIds, ...group.groupIds].map(id => { const child = [...doc.blocks, ...doc.groups].find(e => e.id === id); return <View key={id} style={{ flexDirection: 'row', alignItems: 'center' }}><Button label={child?.title || id} variant="ghost" onPress={() => { void c.select([id]); }} style={{ flex: 1 }} /><IconButton label="Subir" icon="ChevronUp" disabled={disabled} onPress={() => reorder(id, -1)} /><IconButton label="Bajar" icon="ChevronDown" disabled={disabled} onPress={() => reorder(id, 1)} /></View>; })}</Section>}
      <Section onLayout={anchor('communication')} title={e ? 'Instrucción para el agente' : 'Acuerdo de comunicación'}><CommunicationEditor key={e?.id ?? doc.id} value={e?.communication ?? (!e ? doc.communication : undefined)} scope={group ? 'Grupo' : block ? 'Bloque' : 'Documento'} save={editComm} clear={clearComm} disabled={c.offline} inherited={instructionLevels(doc, e).filter(level => level.id !== (e?.id ?? doc.id)).map(level => ({ ...level, label: level.id === doc.id ? 'Documento' : `Grupo «${level.title}»` }))} selectLevel={id => { void c.select(id === doc.id ? [] : [id]); }} /></Section>
      {e && <><Section title="Datos"><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Txt kind="label" muted>ID</Txt><Txt kind="code" selectable style={{ flex: 1 }}>{e.id}</Txt><IconButton label="Copiar ID" icon="Copy" onPress={() => { void copyText(e.id).catch(error => c.fail(error)); }} /></View>{block && <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Txt kind="label" muted>TIPO</Txt><Txt kind="code" selectable style={{ flex: 1 }}>{block.typeId}</Txt></View>}</Section>
        <View style={{ gap: 12, paddingTop: 20, borderTopWidth: 1, borderColor: u.c.border }}><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Button label="Duplicar" icon="CopyPlus" small disabled={disabled} onPress={() => { void c.edit([{ type: 'entity.duplicate', id: e.id, idPrefix: newId('copy') }], 'Duplicar elemento'); }} />{group && <><Button label="Guardar como plantilla" small disabled={disabled} onPress={() => onTemplate(group)} /><Button label="Desagrupar" icon="Ungroup" small disabled={disabled} onPress={() => { void c.edit([{ type: 'group.delete', id: group.id, ungroup: true }], 'Desagrupar'); }} /></>}</View><Button label={group ? 'Eliminar grupo y contenido' : 'Eliminar'} variant="danger" disabled={disabled} onPress={() => { void c.edit([{ type: group ? 'group.delete' : 'block.delete', id: e.id }], 'Eliminar elemento'); }} /></View></>}
      {!e && <><Section onLayout={anchor('activity')} title="Actividad">{c.events.slice(-5).reverse().map(event => <View key={event.id} style={{ gap: 4 }}><Txt kind="small">{event.action.label}</Txt><Delivery event={event} /></View>)}{c.events.some(e => e.status === 'pending' || e.status === 'failed') && <Button label="Enviar pendientes" small disabled={disabled} onPress={() => { void c.task(async () => { const result = await c.api.flush({ workspaceId: c.workspaceId, documentId: doc.id }); c.setEvents(result.events); }); }} />}{!c.events.length && <Txt kind="small" muted>Aún no hay acciones enviadas.</Txt>}</Section><Section onLayout={anchor('history')} title="Historial">{history.slice(-8).reverse().map(tx => <View key={tx.id} style={{ gap: 4 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}><Txt kind="label" muted>REV {tx.revision}</Txt><Icon name={tx.actor === 'agent' ? 'Bot' : tx.actor === 'user' ? 'User' : 'Cog'} size={12} color={u.c.foregroundMuted} /></View><Txt kind="small" muted={tx.kind !== 'edit'}>{tx.label}</Txt><Txt kind="small" muted>{new Date(tx.at).toLocaleString('es')}</Txt></View>)}</Section></>}
    </>}
  </ScrollView></View>;
}
const tokensLabels = { stack: 'Pila', grid: 'Rejilla', flow: 'Flujo', free: 'Libre' } as const;
