import React, { useContext, useEffect, useRef, useState } from 'react';
import { Pressable, View } from 'react-native';
import { Icon, ScrollView, TextInput } from '@getpaseo/plugin/client/react-native';
import type { CanvasGroup, CanvasLink, CanvasOperation } from '../shared/model';
import type { CanvasController } from './useCanvas';
import { Button, CheckRow, Field, IconButton, Modal, Segments, Txt, useUI } from './ui';
import { ancestors, connectOperations, containerMode, hasCommunication, instructionLevels, pinnedChildren, safeUrl, topSelection, type Rect } from './logic';
import { communicationOperation, dataProperties, inlineKeys, layoutIcons, layoutOperations, leaveGroupOperations, reorderOperation, typeSlot } from './panel-actions';
import { isWhiteboardRenderer } from '../shared/whiteboard';
import { resolveScope } from '../shared/learning';
import { variablesSchema } from '../shared/learning';
import { islandStyle } from './whiteboard-visuals';
import { tokens } from './tokens';
import { attachZoomMenu, attachGridKeys, focusInput, activateRendererReset } from './web';
import { usePresentation } from './usePresentation';
import { RegisteredRenderer } from './renderers/RegisteredRenderer';
import { newId } from './logic';
import { SelectionGeometry } from './SelectionOverlay';
import { NumberPropertyField } from './NumberPropertyField';
import { needsContentInteraction } from './interaction';
import { linkTone } from './Links';
import { HiddenResult } from './HiddenResult';
export type ActionPopover = { kind: 'more' | 'instruction' | 'layout' | 'data' | 'text' | 'connect' | 'url' | 'language' | 'status' | 'variables' | 'link-type' | 'link-color'; targetId?: string | null } | null;
const toneNames = { neutro: 'Neutro', acento: 'Acento', violeta: 'Violeta', turquesa: 'Turquesa', aviso: 'Aviso', peligro: 'Peligro' } as const;
export function SelectionActions({ controller: c, panelRoot, disabled, popup, onPopup, ask, add, duplicate, remove, groupSelection, connectSelection, release, template, exportSelection, rects, editText, editLinkLabel, undoNotice, linkId, onLink, interact, availableWidth, availableHeight }: {
  controller: CanvasController; panelRoot: React.RefObject<View | null>; disabled: boolean; popup: ActionPopover; onPopup(value: ActionPopover): void; ask(): void; add(): void; duplicate(): void; remove(): void; groupSelection(): void; connectSelection(): void; release(ids: string[], label?: string): void; template(group: CanvasGroup): void; exportSelection(): void; availableWidth: number; availableHeight: number; rects(): Map<string, Rect>; editText(): void; interact(): void; editLinkLabel(): void; undoNotice(label: string): void;
} & { linkId?: string | null; onLink(id: string | null): void }) {
  const lifetime = useRef(true), liveController = useRef(c); liveController.current = c;
  useEffect(() => { lifetime.current = true; return () => { lifetime.current = false; }; }, []);
  const geometry = useContext(SelectionGeometry), [popupHeight, setPopupHeight] = useState(0);
  const u = useUI(), presentation = usePresentation(c), doc = c.view!.document;
  const selected = [...doc.groups, ...doc.blocks].filter(e => c.selection.includes(e.id)), entity = selected.length === 1 ? selected[0] : undefined;
  const group = entity && 'groupIds' in entity ? entity : undefined, block = entity && 'typeId' in entity ? entity : undefined;
  const type = c.catalog?.blockTypes.find(t => t.id === block?.typeId), slot = typeSlot(type), link = linkId ? doc.links.find(l => l.id === linkId) : undefined;
  const whiteboard = selected.length > 0 && selected.every(e => 'typeId' in e && isWhiteboardRenderer(c.catalog?.blockTypes.find(t => t.id === e.typeId)?.renderer));
  const actionRefs = useRef(new Map<string, { focus?(): void; disabled: boolean }>()), focusedAction = useRef('');
  const host = useRef<View>(null), trigger = useRef<View>(null), [query, setQuery] = useState(''), [toolbarFocus, setToolbarFocus] = useState('');
  const close = () => { onPopup(null); actionRefs.current.get(focusedAction.current)?.focus?.(); }, open = (kind: NonNullable<ActionPopover>['kind'], targetId?: string | null) => onPopup(popup?.kind === kind ? null : { kind, targetId });
  useEffect(() => { setQuery(''); if (!popup || u.compact) return;
    const cleanup = attachZoomMenu(host.current, trigger.current, close, true);
    if (popup.kind === 'connect') focusInput(host.current);
    return cleanup;
  }, [popup?.kind, popup?.targetId, u.compact]);
  useEffect(() => attachGridKeys(trigger.current, key => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(key)) return false; const rows = [...actionRefs.current.entries()].filter(([, item]) => !item.disabled), index = rows.findIndex(([label]) => label === focusedAction.current); const next = key === 'Home' ? 0 : key === 'End' ? rows.length - 1 : (index + (key === 'ArrowLeft' ? -1 : 1) + rows.length) % rows.length; rows[next]?.[1].focus?.(); return rows.length > 0; }), [c.selection.join('|'), linkId]);
  const apply = async (operations: CanvasOperation[], label: string) => { if (disabled || !operations.length) return; return c.edit(operations, label); };
  const patchEntity = (patch: object, label: string) => entity ? apply([{ type: group ? 'group.update' : 'block.update', id: entity.id, patch } as CanvasOperation], label) : Promise.resolve(undefined);
  const updateLink = (patch: Partial<CanvasLink>, label: string) => link ? apply([{ type: 'link.update', id: link.id, patch }], label) : Promise.resolve(undefined);
  const instructionTarget = popup?.targetId === undefined ? entity?.id ?? null : popup.targetId;
  const instructionEntity = instructionTarget ? [...doc.blocks, ...doc.groups].find(e => e.id === instructionTarget) : undefined;
  const communication = instructionEntity?.communication ?? (!instructionTarget ? doc.communication : undefined);
  const saveCommunication = async (patch: Partial<typeof doc.communication>) => {
    if (disabled) return; const documentId = doc.id; await c.settle(); const latest = c.current.current?.document;
    if (!latest || latest.id !== documentId) return;
    return c.edit([communicationOperation(latest, instructionTarget, patch)], 'Editar indicaciones para el asistente');
  };
  const layoutGroup = popup?.targetId === null ? undefined : group, layout = layoutGroup?.layout ?? (!layoutGroup ? doc.layout : undefined), layoutId = layoutGroup?.id ?? null;
  const layoutMode = containerMode(doc, layoutId, c.catalog);
  const saveLayout = (next: NonNullable<CanvasGroup['layout']>) => { try { void apply(layoutOperations(doc, layoutId, next, rects(), c.catalog), layoutGroup ? 'Cambiar disposición del grupo' : 'Cambiar disposición del lienzo'); } catch (error) { c.fail(error); } };
  const resetUnavailable = u.layout.platform !== 'web' && !['controls', 'prediction-gate'].includes(type?.renderer ?? '');
  const reset = async () => {
    if (!block || disabled || resetUnavailable) return;
    const documentId = doc.id, blockId = block.id, root = panelRoot.current; await c.settle();
    const current = () => { const controller = liveController.current, latest = controller.current.current?.document; return lifetime.current && !!root && panelRoot.current === root && !controller.busy && !controller.offline && latest?.id === documentId && latest.workspaceId === doc.workspaceId && controller.selection.length === 1 && controller.selection[0] === blockId && latest.blocks.some(item => item.id === blockId); };
    if (!current()) { if (lifetime.current) c.fail(new Error('No se reinició: el documento o la selección cambió.')); return; }
    if (u.layout.platform === 'web') {
      if (!activateRendererReset(root, blockId, current)) c.fail(new Error('No se reinició: abre el grupo y espera a que el bloque esté disponible.'));
      return;
    }
    const latest = c.current.current!.document;
    if (type?.renderer === 'controls') {
      const variables = resolveScope(latest, blockId, c.learning.getSnapshot());
      for (const name of block.data.variables as string[] ?? []) if (variables[name]) c.learning.setVariable(blockId, name, null);
    } else c.learning.setBlock(blockId, null);
    await c.learning.flush(); if (c.current.current?.document.id !== documentId) return;
    if (['controls', 'function-plot', 'animated-flow', 'glsl-shader', 'step-figure', 'step-sequencer'].includes(type?.renderer ?? '')) await c.send({ kind: type!.renderer + '.reset', label: 'Reiniciar ' + type!.name, payload: {}, targetIds: [blockId], delivery: 'batched', settled: true }, newId('evt'));
  };
  const ungroup = () => { if (group) void apply([{ type: 'group.delete', id: group.id, ungroup: true }], 'Desagrupar').then(next => { if (next) close(); }); };
  const button = (label: string, icon: string, press: () => void, writes = true, active = false, text = false, unavailable = false) => <Pressable key={label} ref={value => { if (value) actionRefs.current.set(label, { focus: () => value.focus(), disabled: unavailable || writes && disabled }); else actionRefs.current.delete(label); }} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled: unavailable || writes && disabled, selected: active }} disabled={unavailable || writes && disabled} onFocus={() => { focusedAction.current = label; setToolbarFocus(label); }} onBlur={() => setToolbarFocus('')} onPress={event => { event.stopPropagation(); press(); }} style={({ pressed }) => ({ minWidth: u.compact ? 44 : 36, height: u.compact ? 44 : 36, paddingHorizontal: text ? tokens.toolbar.labelButton.paddingH : 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: 6, borderWidth: toolbarFocus === label ? 2 : 0, borderColor: u.c.accent, backgroundColor: pressed ? u.c.surface2 : active ? u.wash('acento') : 'transparent', opacity: unavailable || writes && disabled ? .45 : 1 })}><Icon name={icon} size={16} color={active ? u.c.accent : u.c.foregroundMuted} />{text && <Txt kind="button">{label}</Txt>}</Pressable>;
  const row = (label: string, icon: string, press: () => void, writes = true, danger = false, unavailable = false) => <Pressable key={label} accessibilityRole="menuitem" accessibilityLabel={label} accessibilityState={{ disabled: unavailable || writes && disabled }} disabled={unavailable || writes && disabled} onPress={event => { event.stopPropagation(); press(); }} style={({ pressed }) => ({ minHeight: u.compact ? 44 : tokens.menu.row.height, paddingHorizontal: tokens.menu.row.paddingH, borderRadius: tokens.menu.row.radius, flexDirection: 'row', alignItems: 'center', gap: tokens.menu.row.gap, backgroundColor: pressed ? u.c.surface2 : 'transparent', opacity: unavailable || writes && disabled ? .45 : 1 })}><Icon name={icon} size={16} color={danger ? u.c.statusDanger : u.c.foregroundMuted} /><Txt style={{ flex: 1, color: danger ? u.c.statusDanger : u.c.foreground }}>{label}</Txt></Pressable>;
  const moreRows = <>
    {!whiteboard && row('Preguntar', 'MessageCircleQuestion', ask, false)}
    {entity && row(group ? 'Editar título' : 'Editar texto', 'Type', () => { close(); editText(); }, true)}
    {block && needsContentInteraction(type?.renderer) && !u.compact && row('Interactuar', 'MousePointerClick', () => { close(); interact(); }, false)}
    {block && slot && row(slot.label, slot.icon, () => { if (slot.kind === 'reset') void reset().catch(c.fail); else open(slot.kind); }, slot.kind === 'reset', false, slot.kind === 'reset' && resetUnavailable)}
    {block && row('Datos…', 'SlidersHorizontal', () => open('data'), false)}
    {entity && row('Instrucción', 'Compass', () => open('instruction'), false)}
    {group && row('Añadir dentro', 'Plus', () => { close(); add(); })}
    {group && row('Disposición', layoutIcons[containerMode(doc, group.id, c.catalog)], () => open('layout'), false)}
    {group && row(group.collapsed ? 'Desplegar' : 'Plegar', group.collapsed ? 'ChevronDown' : 'ChevronUp', () => { void patchEntity({ collapsed: !group.collapsed }, group.collapsed ? 'Desplegar grupo' : 'Plegar grupo'); close(); })}
    {group?.variables?.length ? row('Variables…', 'SlidersHorizontal', () => open('variables'), false) : null}
    {entity && row('Conectar con…', 'Spline', () => open('connect'), false)}
    {selected.length > 1 && row('Agrupar', 'Group', () => { close(); groupSelection(); })}
    {selected.length === 2 && row('Conectar', 'Spline', () => { close(); connectSelection(); })}
    {row('Duplicar', 'CopyPlus', () => { close(); duplicate(); })}
    {group && row('Desagrupar', 'Ungroup', ungroup)}
    {group && row('Guardar como plantilla…', 'LibraryBig', () => { close(); template(group); })}
    {row('Exportar selección', 'FileOutput', () => { close(); exportSelection(); })}
    {(entity?.position || selected.some(e => e.position)) && row(selected.length > 1 ? 'Soltar posiciones' : 'Soltar posición', 'PinOff', () => { close(); release(selected.filter(e => e.position).map(e => e.id)); })}
    {group && pinnedChildren(doc, group.id).length > 0 && row('Reordenar automáticamente', 'LayoutGrid', () => { close(); release(pinnedChildren(doc, group.id), 'Reordenar automáticamente'); })}
    {selected.length > 0 && selected[0].parentGroupId && selected.every(e => e.parentGroupId === selected[0].parentGroupId) && row('Sacar del grupo', 'LogOut', () => { try { void apply(leaveGroupOperations(doc, c.selection, rects(), c.catalog), 'Sacar del grupo'); close(); } catch (error) { c.fail(error); } })}
    {block?.size && row('Tamaño automático', 'Maximize', () => { void patchEntity({ size: null }, 'Restablecer tamaño automático'); close(); })}
    {entity?.parentGroupId && ['stack', 'grid', 'flow'].includes(containerMode(doc, entity.parentGroupId, c.catalog)) && [-1, 1].map(direction => row(direction < 0 ? 'Mover antes' : 'Mover después', direction < 0 ? 'ChevronUp' : 'ChevronDown', () => { void apply(reorderOperation(doc, entity.id, direction), direction < 0 ? 'Mover antes' : 'Mover después'); }, true, false, !reorderOperation(doc, entity.id, direction).length))}
    {row(group ? 'Eliminar grupo y contenido' : 'Eliminar', 'Trash2', () => { close(); remove(); }, true, true)}
  </>;
  const propertyFields = (textOnly = false) => block && <>
    {(textOnly || u.compact) && <Field key={block.id + ':title'} label="Título" value={block.title} disabled={disabled} onSave={title => patchEntity({ title }, 'Editar título')} />}
    {type ? (textOnly ? type.properties.filter(p => inlineKeys(type.renderer).includes(p.key)) : dataProperties(type, u.compact)).map(p => p.kind === 'boolean' ? <CheckRow key={p.key} label={p.label} checked={!!block.data[p.key]} disabled={disabled} onPress={() => { void patchEntity({ data: { [p.key]: !block.data[p.key] } }, 'Editar ' + p.label); }} /> : p.kind === 'number' ? <NumberPropertyField key={block.id + ':' + p.key} label={p.label} value={String(block.data[p.key] ?? '')} required={p.required} disabled={disabled} save={value => patchEntity({ data: { [p.key]: value } }, 'Editar ' + p.label)} /> : <Field key={block.id + ':' + p.key} label={p.label} required={p.required} value={p.kind === 'json' ? JSON.stringify(block.data[p.key] ?? null, null, 2) : String(block.data[p.key] ?? '')} multiline={p.kind === 'text' || p.kind === 'json'} mono={p.kind !== 'text'} inputStyle={p.kind === 'json' ? { minHeight: 120 } : undefined} disabled={disabled} onSave={value => { let parsed: unknown = value; if (p.kind === 'json') { try { parsed = JSON.parse(value); } catch { throw new Error('JSON no válido'); } } else if (p.kind === 'number') { parsed = Number(value); if (!Number.isFinite(parsed)) throw new Error('Número no válido'); } return patchEntity({ data: { [p.key]: parsed } }, 'Editar ' + p.label); }} />) : <Txt muted>Importa la colección que define este tipo para editar sus propiedades.</Txt>}
  </>;
  const concealed = entity && presentation?.hiddenBy.get(entity.id);
  const ancestorsWithInstructions = instructionLevels(doc, instructionEntity).filter(level => level.id !== instructionTarget && !!level.communication.instructions.trim());
  const connectCandidates = entity ? [...doc.blocks, ...doc.groups].filter(e => e.id !== entity.id && !ancestors(doc, entity).some(g => g.id === e.id) && !ancestors(doc, e).some(g => g.id === entity.id) && !presentation?.hiddenBy.has(e.id) && (!query.trim() || e.title.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))) : [];
  const connectTo = (candidateId: string) => { if (!entity || disabled) return; const documentId = doc.id, result = connectOperations(doc, entity.id, candidateId); const choose = async (id: string) => { await c.select([]); if (c.current.current?.document.id !== documentId) return; onLink(id); close(); }; if (result.existing) void choose(result.existing.id); else void apply(result.operations, 'Conectar elementos').then(next => { if (next && result.id) void choose(result.id); }); };
  const gateData = block && presentation?.activeGates.has(block.id) && (popup?.kind === 'data' || popup?.kind === 'text');
  const content = gateData ? <RegisteredRenderer block={block!} id={type!.renderer!} controller={c} readOnly={disabled} send={async (kind, payload, label, delivery = 'batched') => { await c.send({ kind, payload, label, delivery, targetIds: [block!.id] }, newId('evt')); }} /> : concealed?.length ? <HiddenResult gateIds={concealed} open={id => { close(); void c.select([id]); }} /> : popup?.kind === 'more' ? moreRows : popup?.kind === 'instruction' ? <>
    <Field key={'instruction:' + (instructionTarget ?? doc.id)} label="Instrucción" value={communication?.instructions ?? ''} multiline inputStyle={{ minHeight: 72, maxHeight: 192 }} disabled={disabled} placeholder="Cómo debe hablar el asistente sobre esto" onSave={instructions => saveCommunication({ instructions })} />
    {ancestorsWithInstructions.length > 0 && <><Txt kind="small" muted>También se aplica:</Txt>{ancestorsWithInstructions.map(level => <Button key={level.id} label={level.id === doc.id ? 'Todo el lienzo' : 'Grupo «' + level.title + '»'} icon="Compass" variant="ghost" small onPress={() => { if (level.id === doc.id) { void c.select([]); } else void c.select([level.id]); onPopup({ kind: 'instruction', targetId: level.id === doc.id ? null : level.id }); }} />)}</>}
    {!!communication?.intent && <Txt kind="small" muted>Intención: {communication.intent}</Txt>}
    {!!communication?.audience && <Txt kind="small" muted>Audiencia: {communication.audience}</Txt>}
    {hasCommunication(communication) && <Button label="Vaciar" icon="Eraser" variant="ghost" small disabled={disabled} onPress={() => { void saveCommunication({ instructions: '', intent: '', audience: '' }).then(next => { if (next) undoNotice('Instrucción vaciada'); }); }} />}
  </> : popup?.kind === 'layout' ? <>
    <View style={{ flexDirection: 'row', gap: 4 }}>{(['graph', 'stack', 'grid', 'flow', 'free'] as const).map(mode => <Pressable key={mode} accessibilityRole="button" accessibilityLabel={tokens.layout.labels[mode]} accessibilityState={{ selected: mode === layoutMode, disabled }} disabled={disabled} onPress={() => saveLayout({ ...layout, mode })} style={{ width: 56, height: 48, alignItems: 'center', justifyContent: 'center', gap: 4, borderRadius: 6, borderWidth: mode === layoutMode ? layout ? 1.5 : 1 : 0, borderStyle: !layout ? 'dashed' : 'solid', borderColor: layout ? u.c.accent : u.c.border, backgroundColor: mode === layoutMode && layout ? u.wash('acento') : 'transparent', opacity: disabled ? .45 : 1 }}><Icon name={layoutIcons[mode]} size={20} color={u.c.foreground} /><Txt kind="small">{tokens.layout.labels[mode]}</Txt></Pressable>)}</View>
    {!layout && <Txt kind="small" muted>Automático: se ordena como {tokens.layout.labels[layoutMode === 'rows' ? 'stack' : layoutMode].toLocaleLowerCase()}.</Txt>}
    {layoutMode === 'graph' && <Segments value={layout?.direction ?? 'down'} options={[{ value: 'down', label: 'Hacia abajo' }, { value: 'right', label: 'Hacia la derecha' }]} disabled={disabled} onChange={direction => saveLayout({ ...layout, mode: 'graph', direction })} />}
    {layoutMode === 'grid' && <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Txt>Columnas</Txt><IconButton icon="Minus" label="Menos columnas" disabled={disabled || (layout?.columns ?? 2) <= 1} onPress={() => saveLayout({ ...layout, mode: 'grid', columns: (layout?.columns ?? 2) - 1 })} /><Txt>{layout?.columns ?? 2}</Txt><IconButton icon="Plus" label="Más columnas" disabled={disabled || (layout?.columns ?? 2) >= 4} onPress={() => saveLayout({ ...layout, mode: 'grid', columns: (layout?.columns ?? 2) + 1 })} /></View>}
  </> : popup?.kind === 'data' || popup?.kind === 'text' ? group ? <><Field label="Título" value={group.title} disabled={disabled} onSave={title => patchEntity({ title }, 'Editar título')} /><Field label="Propósito" value={group.description} multiline disabled={disabled} onSave={description => patchEntity({ description }, 'Editar propósito del grupo')} /></> : propertyFields(popup.kind === 'text') : popup?.kind === 'variables' && group ? <Field label="Variables" value={JSON.stringify(group.variables, null, 2)} multiline mono disabled={disabled} onSave={value => patchEntity({ variables: variablesSchema.parse(JSON.parse(value)) }, 'Editar variables del grupo')} /> : popup?.kind === 'connect' ? <>
    <TextInput autoFocus accessibilityLabel="Buscar elemento que conectar" placeholder="Buscar por título" placeholderTextColor={u.c.foregroundMuted} value={query} onChangeText={setQuery} onSubmitEditing={() => { if (connectCandidates[0]) connectTo(connectCandidates[0].id); }} onKeyPress={event => { event.stopPropagation(); if (event.nativeEvent.key === 'Escape') close(); }} style={[u.font('body'), { minHeight: u.compact ? 44 : 32, paddingHorizontal: 10, backgroundColor: u.c.surface2, borderRadius: 6, borderWidth: 1, borderColor: u.c.border }]} />
    {connectCandidates.slice(0, 8).map(candidate => <Pressable key={candidate.id} accessibilityRole="menuitem" accessibilityLabel={candidate.title || candidate.id} disabled={disabled} accessibilityState={{ disabled }} onPress={() => connectTo(candidate.id)} style={{ minHeight: 44, flexDirection: 'row', gap: 8, alignItems: 'center', opacity: disabled ? .45 : 1 }}><Icon name={'groupIds' in candidate ? 'Group' : 'CircleDot'} size={16} color={u.c.foregroundMuted} /><View style={{ flex: 1 }}><Txt>{candidate.title || candidate.id}</Txt><Txt kind="small" muted>{doc.groups.find(parent => parent.id === candidate.parentGroupId)?.title ?? 'Todo el lienzo'}</Txt></View></Pressable>)}
    {!connectCandidates.length && <Txt kind="small" muted>Nada coincide con «{query}».</Txt>}{connectCandidates.length > 8 && <Txt kind="small" muted>{connectCandidates.length - 8} más. Escribe para acotar.</Txt>}
  </> : popup?.kind === 'url' || popup?.kind === 'language' || popup?.kind === 'status' ? block && <>
    <Field key={block.id + ':' + popup.kind} label={popup.kind === 'url' ? 'Enlace' : popup.kind === 'language' ? 'Lenguaje' : 'Estado'} value={String(block.data[popup.kind === 'url' ? 'url' : popup.kind === 'language' ? 'language' : 'status'] ?? '')} mono={popup.kind !== 'status'} disabled={disabled} placeholder={popup.kind === 'url' ? 'https://…' : undefined} helper={popup.kind === 'url' ? 'Hace falta un enlace http o https.' : undefined} onSave={value => { if (popup.kind === 'url' && !safeUrl(value)) throw new Error('VALIDATION'); return patchEntity({ data: { [popup.kind === 'url' ? 'url' : popup.kind === 'language' ? 'language' : 'status']: value } }, 'Editar ' + popup.kind); }} />
    {popup.kind === 'status' && <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{['Listo', 'En curso', 'Bloqueado', 'Nuevo'].map(status => <Button key={status} label={status} small active={block.data.status === status} disabled={disabled} onPress={() => { void patchEntity({ data: { status } }, 'Cambiar estado'); }} />)}</View>}
  </> : popup?.kind === 'link-type' ? (['flow', 'depends', 'reference'] as const).map(kind => <Pressable key={kind} accessibilityRole="menuitem" accessibilityLabel={tokens.graph.kinds[kind]} accessibilityState={{ selected: link?.kind === kind, disabled }} disabled={disabled} onPress={() => { void updateLink({ kind }, 'Cambiar tipo de enlace'); close(); }} style={{ flexDirection: 'row', gap: 8, alignItems: 'center', minHeight: 44, opacity: disabled ? .45 : 1 }}><View style={{ width: 28, height: 1, borderTopWidth: 1.5, borderColor: u.c.foregroundMuted, borderStyle: kind === 'flow' ? 'solid' : kind === 'depends' ? 'dashed' : 'dotted' }} /><View style={{ flex: 1 }}><Txt>{tokens.graph.kinds[kind]}</Txt><Txt kind="small" muted>{tokens.graph.kindHelp[kind]}</Txt></View>{link?.kind === kind && <Icon name="Check" size={14} color={u.c.accent} />}</Pressable>) : popup?.kind === 'link-color' && link ? <View accessibilityRole="radiogroup" style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{[undefined, ...tokens.graph.tones].map(tone => <Pressable key={tone ?? 'auto'} accessibilityRole="radio" accessibilityLabel={tone ? toneNames[tone] : 'Automático'} accessibilityState={{ checked: link.tone === tone, disabled }} disabled={disabled} onPress={() => { if (tone) void updateLink({ tone }, 'Cambiar color del enlace'); else { const { tone: _tone, ...rest } = link; void apply([{ type: 'link.delete', id: link.id }, { type: 'link.create', link: rest }], 'Quitar color del enlace'); } close(); }} style={{ width: 24, height: 24, borderRadius: 12, backgroundColor: tone ? u.tone(linkTone({ kind: link.kind, tone })) : u.c.surface2, borderWidth: link.tone === tone ? 2 : 1, borderColor: link.tone === tone ? u.c.accent : u.c.border, opacity: disabled ? .45 : 1 }} />)}</View> : null;
  const toolbar = <View ref={trigger} nativeID="lienzo-interactive-selection-toolbar" style={u.compact ? { height: 48, borderTopWidth: 1, borderColor: u.c.border, backgroundColor: u.c.surface1 } : [islandStyle(u, true), { minHeight: tokens.toolbar.height }]}><ScrollView horizontal contentContainerStyle={{ alignItems: 'center', flexDirection: 'row' }}>
    {link ? <>
      {button('Etiqueta', 'Type', editLinkLabel)}{button('Tipo', link.kind === 'flow' ? 'Minus' : link.kind === 'depends' ? 'MoreHorizontal' : 'Ellipsis', () => open('link-type'), false)}{<Pressable ref={value => { if (value) actionRefs.current.set('Color', { focus: () => value.focus(), disabled: false }); else actionRefs.current.delete('Color'); }} onFocus={() => { focusedAction.current = 'Color'; }} accessibilityRole="button" accessibilityLabel="Color" onPress={() => open('link-color')} style={{ width: u.compact ? 44 : 36, height: u.compact ? 44 : 36, justifyContent: 'center', alignItems: 'center' }}><View style={{ width: 20, height: 20, borderRadius: 10, backgroundColor: u.tone(linkTone(link)), borderWidth: 1, borderColor: u.c.border }} /></Pressable>}{button('Invertir', 'ArrowLeftRight', () => { void updateLink({ from: link.to, to: link.from }, 'Invertir enlace'); })}{button('Eliminar', 'Trash2', remove)}
    </> : <>
      {!whiteboard && button('Preguntar', 'MessageCircleQuestion', ask, false, false, true)}
      {!whiteboard && block && (u.compact ? button('Editar', 'SlidersHorizontal', () => open('data'), false) : slot && button(slot.label, slot.icon, () => { if (slot.kind === 'reset') void reset().catch(c.fail); else open(slot.kind); }, slot.kind === 'reset', false, false, slot.kind === 'reset' && resetUnavailable))}
      {!whiteboard && group && <>{button('Añadir dentro', 'Plus', add)}{button('Disposición', layoutIcons[containerMode(doc, group.id, c.catalog)], () => open('layout'), false)}</>}
      {!whiteboard && entity && button('Instrucción', 'Compass', () => open('instruction'), false, hasCommunication(entity.communication))}
      {!whiteboard && selected.length > 1 && <>{button('Agrupar', 'Group', groupSelection)}{selected.length === 2 && button('Conectar', 'Spline', connectSelection)}</>}
      {!whiteboard && group ? button('Desagrupar', 'Ungroup', ungroup) : <>{button('Duplicar', 'CopyPlus', duplicate)}{button('Eliminar', 'Trash2', remove)}</>}
      {button('Más', 'Ellipsis', () => open('more'), false)}
    </>}
  </ScrollView></View>;
  const roomBelow = geometry ? geometry.height - geometry.top - tokens.toolbar.height - tokens.popover.offset - 8 : availableHeight - 180, roomAbove = geometry ? geometry.top - tokens.popover.offset - 68 : 0;
  const openAbove = popupHeight > roomBelow && roomAbove > roomBelow;
  const popupTitle = popup?.kind === 'instruction' ? 'Instrucción' : popup?.kind === 'layout' ? 'Disposición' : popup?.kind === 'data' ? type?.name ?? 'Datos' : popup?.kind === 'connect' ? 'Conectar con…' : popup?.kind === 'more' ? 'Más' : popup?.kind === 'link-type' ? 'Tipo' : popup?.kind === 'link-color' ? 'Color' : popup?.kind === 'variables' ? 'Variables' : popup?.kind === 'text' ? 'Editar texto' : slot?.label ?? 'Datos';
  return <View pointerEvents="box-none" style={{ alignItems: 'center', maxWidth: Math.max(0, availableWidth - 16), ...(popup && !u.compact ? { minWidth: Math.min(availableWidth - 16, popup.kind === 'more' ? tokens.menu.width : ['url', 'language', 'status', 'link-color'].includes(popup.kind) ? tokens.popover.width.small : tokens.popover.width.medium) } : {}) }}>{(selected.length > 0 || link) && toolbar}
    {u.compact ? <Modal title={popupTitle} open={!!popup} onOpenChange={value => { if (!value) close(); }}><Modal.Content><View nativeID="lienzo-interactive-selection-popover" style={{ gap: 12 }}>{content}</View></Modal.Content></Modal> : popup && <View ref={host} onLayout={event => setPopupHeight(event.nativeEvent.layout.height)} nativeID="lienzo-interactive-selection-popover" style={[islandStyle(u, true), { position: 'absolute', ...(openAbove ? { bottom: tokens.toolbar.height + tokens.popover.offset } : { top: (selected.length > 0 || link ? tokens.toolbar.height : 0) + tokens.popover.offset }), width: popup.kind === 'more' ? tokens.menu.width : ['url', 'language', 'status', 'link-color'].includes(popup.kind) ? tokens.popover.width.small : tokens.popover.width.medium, maxWidth: Math.max(0, availableWidth - 16), padding: tokens.popover.padding, gap: tokens.popover.gap, zIndex: 11 }]}><View style={{ flexDirection: 'row', alignItems: 'center' }}><Txt kind="bodyStrong" style={{ flex: 1 }}>{popupTitle}</Txt><IconButton label="Cerrar" icon="X" onPress={close} /></View><ScrollView style={{ maxHeight: Math.min(tokens.popover.maxHeight, Math.max(80, Math.max(roomBelow, roomAbove) - 64)) }} contentContainerStyle={{ gap: 12 }}>{content}</ScrollView></View>}
  </View>;
}
