const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
 const pages=await(await fetch('http://127.0.0.1:9222/json/list')).json();
 const page=pages.find(p=>p.type==='page'&&p.url.startsWith('http://127.0.0.1:8765/'));if(!page)throw Error('QA page missing');
 const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((ok,no)=>{ws.addEventListener('open',ok,{once:true});ws.addEventListener('error',no,{once:true});});
 let seq=0;const pending=new Map(),uncaught=[];
 ws.addEventListener('message',e=>{const r=JSON.parse(e.data);if(r.method==='Runtime.exceptionThrown' && r.params.exceptionDetails.url?.includes('real.js'))uncaught.push(r.params.exceptionDetails);if(r.id){const p=pending.get(r.id);if(!p)return;pending.delete(r.id);clearTimeout(p.timer);r.error?p.no(Error(JSON.stringify(r.error))):p.ok(r.result);}});
 const call=(method,params={})=>new Promise((ok,no)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);no(Error('Timeout '+method));},15000);pending.set(id,{ok,no,timer});ws.send(JSON.stringify({id,method,params}));});
 const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value;};
 const wait=async expression=>{for(let n=0;n<150;n++){if(await ev(expression))return;await new Promise(r=>setTimeout(r,50));}throw Error('Condition timed out: '+expression);};
 const box=async selector=>{const r=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})()`);return r;};
 const mouse=(type,x,y,button='left',buttons=0)=>call('Input.dispatchMouseEvent',{type,x,y,button,buttons,clickCount:1});
 const click=async(selector,offset)=>{await wait(`!!document.querySelector(${JSON.stringify(selector)}) && document.querySelector(${JSON.stringify(selector)}).getAttribute('aria-disabled')!=='true'`);await ev('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');const b=await box(selector),x=b.x+(offset?.x??b.w/2),y=b.y+(offset?.y??b.h/2);await mouse('mousePressed',x,y,'left',1);await mouse('mouseReleased',x,y);};
 const drag=async(selector,dx,dy,button='left',offset)=>{const b=await box(selector),x=b.x+(offset?.x??70),y=b.y+(offset?.y??b.h-20),bits=button==='middle'?4:1;await mouse('mouseMoved',x,y);await mouse('mousePressed',x,y,button,bits);for(let i=1;i<=20;i++){await mouse('mouseMoved',x+dx*i/20,y+dy*i/20,button,bits);await new Promise(r=>setTimeout(r,9));}if(button==='middle')await new Promise(r=>setTimeout(r,120));await mouse('mouseReleased',x+dx,y+dy,button);};
 const key=async(key,code,modifiers=0)=>{await call('Input.dispatchKeyEvent',{type:'keyDown',key,code,modifiers});await call('Input.dispatchKeyEvent',{type:'keyUp',key,code,modifiers});};
 const label=text=>'[aria-label='+JSON.stringify(text)+']';
 const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/lienzo-panel-'+name+'.png',Buffer.from(r.data,'base64'));};
 const checks=[];const check=async(name,run)=>{try{await run();checks.push({name,result:'pass'});console.log('PASS '+name);}catch(error){checks.push({name,result:'fail',error:error.message});console.log('FAIL '+name+': '+error.message);throw error;}};
 const pause=ms=>new Promise(r=>setTimeout(r,ms));
 const select=async id=>{await click('#lienzo-entity-'+id);await wait('__panelQA.doc().selectedIds.includes('+JSON.stringify(id)+')');await pause(250);};
 const toolbar=text=>'#lienzo-interactive-selection-toolbar '+label(text);
 const fill=async(selector,value)=>{await ev('document.querySelector('+JSON.stringify(selector)+')?.scrollIntoView({block:"nearest"})');await click(selector);await ev('document.activeElement.select()');await call('Input.insertText',{text:value});await key('Tab','Tab');await pause(750);};
 try {
 await call('Runtime.enable');await call('Page.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:'http://127.0.0.1:8765/?theme=papel'});await wait('!!document.querySelector("#lienzo-entity-note")');await pause(400);
 await check('one node has approved toolbar and Preguntar focuses without sending',async()=>{await select('server');await wait('!!document.querySelector('+JSON.stringify(toolbar('Instrucción'))+')');await click(toolbar('Preguntar'));assert.equal(await ev('document.activeElement.getAttribute("aria-label")'),'Escribir al asistente');assert.equal(await ev('__panelQA.actions.length'),0);await shot('node-toolbar');});
 await check('Estado writes through real block.update and keeps authored data',async()=>{await click(toolbar('Estado'));await click('#lienzo-interactive-selection-popover '+label('Bloqueado'));await wait('__panelQA.doc().blocks.find(b=>b.id==="server").data.status==="Bloqueado"');assert.equal(await ev('__panelQA.doc().blocks.find(b=>b.id==="server").data.kind'),'MODULE');assert.equal(await ev('__panelQA.log.at(-1).operations[0].type'),'block.update');});
 await check('instruction persists and preserves intent/audience',async()=>{await key('Escape','Escape');await ev(`__panelQA.seed([{type:'block.update',id:'server',patch:{communication:{instructions:'',intent:'Intención previa',audience:'Lectores'}}}])`);await pause(1700);await click(toolbar('Instrucción'));await fill('#lienzo-interactive-selection-popover textarea','Explica cada paso');assert.equal(await ev('__panelQA.doc().blocks.find(b=>b.id==="server").communication.instructions'),'Explica cada paso');assert.equal(await ev('__panelQA.doc().blocks.find(b=>b.id==="server").communication.intent'),'Intención previa');await shot('instruction');await key('Escape','Escape');});
 await check('Más contains bounded named actions, Conectar selects existing link',async()=>{await click(toolbar('Más'));await wait('!!document.querySelector("#lienzo-interactive-selection-popover [role=menuitem]")');assert.equal(await ev('document.querySelector("#lienzo-interactive-selection-popover").innerText.includes("Historial")'),false);await click('#lienzo-interactive-selection-popover '+label('Conectar con…'));await call('Input.insertText',{text:'Nota'});assert.equal(await ev('document.activeElement.value'),'Nota');await key('Home','Home');assert.equal(await ev('document.activeElement.getAttribute("aria-label")'),'Buscar elemento que conectar');await key('Enter','Enter');await wait('__panelQA.doc().selectedIds.length===0');await wait('!!document.querySelector('+JSON.stringify(toolbar('Etiqueta'))+')');});
 await check('connection label Escape cancels without write, Enter saves link.update',async()=>{const count=await ev('__panelQA.log.length');await click(toolbar('Etiqueta'));await wait('!!document.querySelector('+JSON.stringify(label('Etiqueta del enlace'))+')');await call('Input.insertText',{text:'Cancelado'});await key('Escape','Escape');await pause(250);assert.equal(await ev('__panelQA.log.length'),count);assert.equal(await ev('__panelQA.doc().links[0].label??""'),'');await click(toolbar('Etiqueta'));await call('Input.insertText',{text:'Entrega datos'});await key('Enter','Enter');await wait('__panelQA.doc().links[0].label==="Entrega datos"');assert.equal(await ev('__panelQA.log.at(-1).operations[0].type'),'link.update');await shot('connection-toolbar');});
 await check('link type, color automatic and inverse preserve label',async()=>{await click(toolbar('Tipo'));await click('#lienzo-interactive-selection-popover '+label('Depende'));await wait('__panelQA.doc().links[0].kind==="depends"');await click(toolbar('Color'));await click('#lienzo-interactive-selection-popover '+label('Violeta'));await wait('__panelQA.doc().links[0].tone==="violeta"');await click(toolbar('Color'));await click('#lienzo-interactive-selection-popover '+label('Automático'));await wait('__panelQA.doc().links[0].tone===undefined');await click(toolbar('Invertir'));await wait('__panelQA.doc().links[0].from==="note"');assert.equal(await ev('__panelQA.doc().links[0].label'),'Entrega datos');});
 await check('group toolbar layout and add inside use real transactions',async()=>{await select('frame');await click(toolbar('Disposición'));await click('#lienzo-interactive-selection-popover '+label('Rejilla'));await wait('__panelQA.doc().groups.find(g=>g.id==="frame").layout.mode==="grid"');await click('#lienzo-interactive-selection-popover '+label('Más columnas'));await wait('__panelQA.doc().groups.find(g=>g.id==="frame").layout.columns===3');await key('Escape','Escape');await click(toolbar('Añadir dentro'));await wait('!!document.querySelector("[role=dialog]")');await click('[role=dialog] '+label('Nota'));await wait('__panelQA.doc().groups.find(g=>g.id==="frame").blockIds.length===1');assert.equal(await ev('__panelQA.doc().blocks.at(-1).parentGroupId'),'frame');});
 await check('multi-selection groups/ungroups without opening generic details',async()=>{await select('server');const note=await box('#lienzo-entity-note');await call('Input.dispatchMouseEvent',{type:'mousePressed',x:note.x+20,y:note.y+16,button:'left',buttons:1,modifiers:8,clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:note.x+20,y:note.y+16,button:'left',buttons:0,modifiers:8,clickCount:1});await wait('__panelQA.doc().selectedIds.length===2');await click(toolbar('Agrupar'));await wait('__panelQA.doc().groups.some(g=>g.blockIds.includes("server")&&g.blockIds.includes("note"))');assert.equal(await ev('!!document.querySelector("[role=dialog]")'),false);const group=await ev('__panelQA.doc().selectedIds[0]');await shot('group-toolbar');await click(toolbar('Desagrupar'));await wait('!__panelQA.doc().groups.some(g=>g.id==='+JSON.stringify(group)+')');assert.equal(await ev('__panelQA.doc().blocks.find(b=>b.id==="server").parentGroupId'),null);});
 await check('inheritance opens group and whole-document instructions with no inspector',async()=>{const child=await ev('__panelQA.doc().groups.find(g=>g.id==="frame").blockIds[0]');await ev(`__panelQA.seed([{type:'group.update',id:'frame',patch:{communication:{instructions:'Parent rule',intent:'',audience:''}}},{type:'communication.set',communication:{instructions:'Canvas rule',intent:'',audience:''}}])`);await pause(1700);await select(child);await click(toolbar('Instrucción'));await wait('document.querySelector("#lienzo-interactive-selection-popover")?.innerText.includes("También se aplica")');await click('#lienzo-interactive-selection-popover '+label('Grupo «Grupo de prueba»'));await wait('__panelQA.doc().selectedIds[0]==="frame"');await wait('document.querySelector("#lienzo-interactive-selection-popover textarea")?.value==="Parent rule"');await click('#lienzo-interactive-selection-popover '+label('Todo el lienzo'));await wait('__panelQA.doc().selectedIds.length===0');await wait('document.querySelector("#lienzo-interactive-selection-popover textarea")?.value==="Canvas rule"');assert.equal(await ev('!!document.querySelector("[role=dialog]")'),false);await shot('inherited-document');await key('Escape','Escape');});
 await check('Vaciar clears three fields and undo restores the instruction',async()=>{await select('server');await click(toolbar('Instrucción'));await click('#lienzo-interactive-selection-popover '+label('Vaciar'));await wait('__panelQA.doc().blocks.find(b=>b.id==="server").communication.instructions===""');assert.equal(await ev('__panelQA.doc().blocks.find(b=>b.id==="server").communication.intent'),'');await key('Escape','Escape');await click(label('Deshacer'));await wait('__panelQA.doc().blocks.find(b=>b.id==="server").communication.instructions==="Explica cada paso"');});
 await check('failed data write keeps authored state and shows honest failure',async()=>{await select('server');await click(toolbar('Estado'));await ev('__panelQA.failNext()');await click('#lienzo-interactive-selection-popover '+label('Listo'));await wait('__panelQA.errors.some(e=>e.error.includes("rejected save"))');assert.equal(await ev('__panelQA.doc().blocks.find(b=>b.id==="server").data.status'),'Bloqueado');await wait('document.body.innerText.includes("No se guardó el cambio")');await key('Escape','Escape');});
 await check('toolbar arrows move focus; keyboard duplicate remains transactional',async()=>{await select('server');await click(toolbar('Preguntar'));await select('server');await click(toolbar('Más'));await key('Escape','Escape');await key('Home','Home');assert.equal(await ev('document.activeElement.getAttribute("aria-label")'),'Preguntar');await key('End','End');assert.equal(await ev('document.activeElement.getAttribute("aria-label")'),'Más');await select('server');const before=await ev('__panelQA.doc().blocks.length');await key('d','KeyD',2);await wait('__panelQA.doc().blocks.length>'+before);assert.equal(await ev('__panelQA.log.at(-1).operations[0].type'),'entity.duplicate');});
 await check('toolbar Reiniciar clears runtime, sends existing settled reset event and preserves scope/authored data',async()=>{await ev(`__panelQA.seed([{type:'document.update',variables:[{name:'x',value:2,min:0,max:10}]},{type:'block.create',block:{id:'fig',typeId:'step-figure',title:'Figura de prueba',position:{x:500,y:300},size:{width:350,height:420},data:__panelQA.catalog.blockTypes.find(t=>t.id==='step-figure').defaults}}])`);await pause(1700);await click('#lienzo-grab-fig-header');await wait('__panelQA.doc().selectedIds[0]==="fig"');await click('#lienzo-entity-fig '+label('Siguiente'));await wait('__panelQA.runtime().blocks.fig?.step===1');const before=await ev('JSON.stringify(__panelQA.doc().blocks.find(b=>b.id==="fig").data)'),revision=await ev('__panelQA.doc().revision');await click(toolbar('Reiniciar'));await wait('__panelQA.runtime().blocks.fig===undefined');await wait('__panelQA.actions.some(a=>a.kind==="step-figure.reset"&&a.settled===true)');assert.equal(await ev('__panelQA.doc().revision'),revision);assert.equal(await ev('JSON.stringify(__panelQA.doc().blocks.find(b=>b.id==="fig").data)'),before);});
 await check('Datos validates JSON before any write and retains authored values',async()=>{await click(toolbar('Más'));await click('#lienzo-interactive-selection-popover '+label('Datos…'));const count=await ev('__panelQA.log.length');await fill('#lienzo-interactive-selection-popover '+label('Pasos y parches'),'not JSON');assert.equal(await ev('__panelQA.log.length'),count);assert.ok(await ev('document.querySelector("#lienzo-interactive-selection-popover").innerText.includes("No se guardó")'));await shot('json-validation');await key('Escape','Escape');});
 await check('toolbar sequencer reset stops local audio, cancels pending pattern and emits exactly one reset',async()=>{
  await ev(`(()=>{const contexts=[];globalThis.__audioQA={contexts};class Context {constructor(){this.state='suspended';this.started=performance.now();this.destination={};this.onstatechange=null;this.oscillators=[];contexts.push(this);}get currentTime(){return(performance.now()-this.started)/1000;}resume(){this.state='running';return Promise.resolve();}close(){this.state='closed';this.closed=true;return Promise.resolve();}createGain(){return{connect(){},disconnect(){},gain:{setValueAtTime(){},linearRampToValueAtTime(){}}};}createOscillator(){const o={connect(){},disconnect(){},frequency:{setValueAtTime(){}},start(){o.started=true;},stop(){o.stops=(o.stops||0)+1;},onended:null};this.oscillators.push(o);return o;}}globalThis.AudioContext=Context;})()`);
  await ev(`__panelQA.seed([{type:'block.create',block:{id:'seq',typeId:'step-sequencer',title:'Secuenciador de prueba',position:{x:780,y:100},size:{width:560,height:620},data:__panelQA.catalog.blockTypes.find(t=>t.id==='step-sequencer').defaults}}])`);await pause(1700);
  await click('#lienzo-grab-seq-header',{x:30,y:16});await wait('__panelQA.doc().selectedIds[0]==="seq"');
  await click('#lienzo-entity-seq '+label('Reproducir'));await wait('__audioQA.contexts.some(c=>c.state==="running"&&c.oscillators.length>0)');
  await click('#lienzo-interactive-sequencer-cell-seq-0-0');await wait('__panelQA.runtime().blocks.seq!==undefined');
  const writes=await ev('__panelQA.log.length'), count=await ev('__panelQA.actions.length'), resets=await ev('__panelQA.actions.filter(a=>a.kind==="step-sequencer.reset").length');
  await click(toolbar('Reiniciar'));await wait('__audioQA.contexts.every(c=>c.closed)');await wait('__panelQA.runtime().blocks.seq===undefined');await wait('__panelQA.actions.filter(a=>a.kind==="step-sequencer.reset").length==='+ (resets+1));await pause(800);
  assert.equal(await ev('__panelQA.log.length'),writes);assert.equal(await ev('__panelQA.actions.length'),count+1);assert.ok(await ev('__audioQA.contexts[0].oscillators.every(o=>o.stops>=2)'));assert.ok(await ev('!!document.querySelector("#lienzo-entity-seq '+label('Reproducir').replaceAll('"','\\"')+'")'));await shot('sequencer-reset');
 });
 await check('rejected sequencer reset has visible error and zero live contexts, no success event',async()=>{
  await click('#lienzo-interactive-sequencer-cell-seq-0-0');await wait('__panelQA.runtime().blocks.seq!==undefined');await pause(800);
  await click('#lienzo-entity-seq '+label('Reproducir'));await wait('__audioQA.contexts.some(c=>c.state==="running")');
  const count=await ev('__panelQA.actions.filter(a=>a.kind==="step-sequencer.reset").length');await ev('__panelQA.failNextRuntime()');await click(toolbar('Reiniciar'));
  await wait('__audioQA.contexts.every(c=>c.closed)');await wait('__panelQA.errors.some(e=>e.error.includes("rejected runtime reset"))');await wait('document.querySelector("#lienzo-entity-seq").innerText.includes("No se pudo guardar el patrón")');
  assert.equal(await ev('__panelQA.actions.filter(a=>a.kind==="step-sequencer.reset").length'),count);assert.ok(await ev('__panelQA.runtime().blocks.seq!==undefined'));await shot('sequencer-reset-rejected');
 });
 await check('dark theme keeps scoped menus bounded and blank pan passes next to toolbar',async()=>{
  await call('Page.navigate',{url:'http://127.0.0.1:8765/?theme=tinta'});await wait('!!document.querySelector("#lienzo-entity-note")');await select('server');await click(toolbar('Más'));await wait('!!document.querySelector("#lienzo-interactive-selection-popover")');const menu=await box('#lienzo-interactive-selection-popover');assert.ok(menu.x>=8&&menu.x+menu.w<=1440&&menu.y>=0&&menu.y+menu.h<=1000);await shot('dark-more');await key('Escape','Escape');await drag('#lienzo-entity-note',40,30,'middle');await wait('!!document.querySelector("#lienzo-interactive-selection-toolbar")');
 });
 await check('compact docks 48px selection toolbar above composer and opens host sheet',async()=>{await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:'http://127.0.0.1:8765/?theme=papel&compact=1'});await wait('!!document.querySelector("#lienzo-composer")');await pause(400);assert.ok(await ev('!!document.querySelector('+JSON.stringify(label('Añadir'))+')'));assert.ok(await ev('!!document.querySelector('+JSON.stringify(label('Deshacer'))+')'));await click('#lienzo-grab-server');await wait('!!document.querySelector("#lienzo-interactive-selection-toolbar")');const bar=await box('#lienzo-interactive-selection-toolbar'),composer=await box('#lienzo-composer');assert.equal(bar.h,48);assert.ok(Math.abs(bar.y+bar.h-composer.y)<2);await click(toolbar('Editar'));await wait('!!document.querySelector("[role=dialog]")');assert.ok(await ev('!!document.querySelector("[role=dialog] '+label('Título').replaceAll('"','\\"')+'")'));await shot('compact-data');});
 assert.deepEqual(uncaught,[]);
 } finally {fs.writeFileSync('/tmp/lienzo-panel-results.json',JSON.stringify({checks,uncaught},null,2));ws.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
